<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array(  ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array(  ) ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array( 'image' ),
'top' => array( 'changepwd_success_header' ),
'grid' => array( 'changepwd_success_message' ),
'footer' => array( 'changepwd_success_back',
'custom_button' ) ),
'formXtTags' => array(  ),
'itemForms' => array( 'image' => 'supertop',
'changepwd_success_header' => 'top',
'changepwd_success_message' => 'grid',
'changepwd_success_back' => 'footer',
'custom_button' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'changepwd_success_message' => array( 'changepwd_success_message' ),
'changepwd_success_back' => array( 'changepwd_success_back' ),
'changepwd_success_header' => array( 'changepwd_success_header' ),
'image' => array( 'image' ),
'custom_button' => array( 'custom_button' ) ),
'cellMaps' => array(  ) ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => true,
'customButtons' => array( 'BtnRedir' ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array( 'BtnRedir' ) ) );
			$pageArray = array( 'id' => 'changepwd_success',
'type' => 'changepwd_success',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'image' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'changepwd-success-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'changepwd_success_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'changepwd-success-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'changepwd_success_message' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'changepwd-success-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'changepwd_success_back',
'custom_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'changepwd_success_message' => array( 'type' => 'changepwd_success_message' ),
'changepwd_success_back' => array( 'type' => 'changepwd_success_back',
'icon' => array( 'fa' => 'arrow-left' ) ),
'changepwd_success_header' => array( 'type' => 'changepwd_success_header' ),
'image' => array( 'type' => 'image',
'image' => array( 'image' => 'mincit_300x50.jpg',
'source' => 2 ) ),
'custom_button' => array( 'eventId' => 'BtnRedir',
'label' => array( 'text' => 'Ingresar ',
'type' => 0 ),
'type' => 'custom_button',
'buttonStyle' => 'success',
'icon' => array( 'glyph' => 'log-in' ) ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>