<?php
			$optionsArray = array( 'details' => array( 'compromisofuncional' => array( 'displayPreview' => 2,
'previewPageId' => '' ),
'comportamental_comun' => array( 'displayPreview' => 2,
'previewPageId' => '' ),
'comportamental_jerarquica' => array( 'displayPreview' => 2,
'previewPageId' => '' ) ),
'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 'evaluado_email',
'idEvaluado',
'evaluado_doc',
'evaluado_nombre',
'evaluado_cargo',
'evaluado_nombramiento',
'evaluado_dep_sup',
'evaluado_dep',
'id_comportamental_fk',
'periodo',
'fchCreacion',
'vigencia',
'evaluado_fechai_po',
'evaluado_fechaf_po',
'estado',
'evaluador_doc',
'evaluador_nombre',
'evaluador_cargo',
'evaluador_nombramiento',
'evaluador_dep_sup',
'evaluador_dep',
'idEvaluador',
'evaluador_email' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'evaluado_email' => array( 'integrated_edit_field17' ),
'idEvaluado' => array( 'integrated_edit_field' ),
'evaluado_doc' => array( 'integrated_edit_field14' ),
'evaluado_nombre' => array( 'integrated_edit_field15' ),
'evaluado_cargo' => array( 'integrated_edit_field16' ),
'evaluado_nombramiento' => array( 'integrated_edit_field27' ),
'evaluado_dep_sup' => array( 'integrated_edit_field18' ),
'evaluado_dep' => array( 'integrated_edit_field19' ),
'id_comportamental_fk' => array( 'integrated_edit_field2' ),
'periodo' => array( 'integrated_edit_field5' ),
'fchCreacion' => array( 'integrated_edit_field6' ),
'vigencia' => array( 'integrated_edit_field4' ),
'evaluado_fechai_po' => array( 'integrated_edit_field20' ),
'evaluado_fechaf_po' => array( 'integrated_edit_field21' ),
'estado' => array( 'integrated_edit_field8' ),
'evaluador_doc' => array( 'integrated_edit_field22' ),
'evaluador_nombre' => array( 'integrated_edit_field23' ),
'evaluador_cargo' => array( 'integrated_edit_field24' ),
'evaluador_nombramiento' => array( 'integrated_edit_field26' ),
'evaluador_dep_sup' => array( 'integrated_edit_field9' ),
'evaluador_dep' => array( 'integrated_edit_field10' ),
'idEvaluador' => array( 'edit_field_label',
'edit_field_tooltip',
'integrated_edit_field1' ),
'evaluador_email' => array( 'integrated_edit_field25' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'add_message',
'step_nav' ),
'below-grid' => array( 'next_step',
'add_save',
'add_back_list',
'add_cancel' ),
'supertop' => array( 'expand_menu_button',
'expand_menu_button1',
'collapse_button',
'loginform_login',
'username_button' ),
'left' => array( 'logo1',
'expand_button',
'menu' ),
'top' => array( 'add_header' ),
'grid' => array( 'integrated_edit_field17',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field27',
'integrated_edit_field18',
'integrated_edit_field19',
'integrated_edit_field2' ),
'step3' => array( 'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field4',
'integrated_edit_field20',
'integrated_edit_field21' ),
'step2' => array( 'integrated_edit_field22',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field26',
'integrated_edit_field9',
'integrated_edit_field10',
'edit_field_label',
'edit_field_tooltip',
'integrated_edit_field1',
'integrated_edit_field25',
'integrated_edit_field',
'integrated_edit_field8' ) ),
'formXtTags' => array(  ),
'itemForms' => array( 'add_message' => 'above-grid',
'step_nav' => 'above-grid',
'next_step' => 'below-grid',
'add_save' => 'below-grid',
'add_back_list' => 'below-grid',
'add_cancel' => 'below-grid',
'expand_menu_button' => 'supertop',
'expand_menu_button1' => 'supertop',
'collapse_button' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'logo1' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'add_header' => 'top',
'integrated_edit_field17' => 'grid',
'integrated_edit_field14' => 'grid',
'integrated_edit_field15' => 'grid',
'integrated_edit_field16' => 'grid',
'integrated_edit_field27' => 'grid',
'integrated_edit_field18' => 'grid',
'integrated_edit_field19' => 'grid',
'integrated_edit_field2' => 'grid',
'integrated_edit_field5' => 'step3',
'integrated_edit_field6' => 'step3',
'integrated_edit_field4' => 'step3',
'integrated_edit_field20' => 'step3',
'integrated_edit_field21' => 'step3',
'integrated_edit_field22' => 'step2',
'integrated_edit_field23' => 'step2',
'integrated_edit_field24' => 'step2',
'integrated_edit_field26' => 'step2',
'integrated_edit_field9' => 'step2',
'integrated_edit_field10' => 'step2',
'edit_field_label' => 'step2',
'edit_field_tooltip' => 'step2',
'integrated_edit_field1' => 'step2',
'integrated_edit_field25' => 'step2',
'integrated_edit_field' => 'step2',
'integrated_edit_field8' => 'step2' ),
'itemLocations' => array( 'integrated_edit_field17' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field14' => array( 'location' => 'grid',
'cellId' => 'c6' ),
'integrated_edit_field15' => array( 'location' => 'grid',
'cellId' => 'c7' ),
'integrated_edit_field16' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_edit_field27' => array( 'location' => 'grid',
'cellId' => 'c2' ),
'integrated_edit_field18' => array( 'location' => 'grid',
'cellId' => 'c8' ),
'integrated_edit_field19' => array( 'location' => 'grid',
'cellId' => 'c9' ),
'integrated_edit_field2' => array( 'location' => 'grid',
'cellId' => 'c11' ),
'integrated_edit_field5' => array( 'location' => 'step3',
'cellId' => 'c4' ),
'integrated_edit_field6' => array( 'location' => 'step3',
'cellId' => 'c5' ),
'integrated_edit_field4' => array( 'location' => 'step3',
'cellId' => 'c6' ),
'integrated_edit_field20' => array( 'location' => 'step3',
'cellId' => 'c8' ),
'integrated_edit_field21' => array( 'location' => 'step3',
'cellId' => 'c9' ),
'integrated_edit_field22' => array( 'location' => 'step2',
'cellId' => 'c1' ),
'integrated_edit_field23' => array( 'location' => 'step2',
'cellId' => 'c' ),
'integrated_edit_field24' => array( 'location' => 'step2',
'cellId' => 'c4' ),
'integrated_edit_field26' => array( 'location' => 'step2',
'cellId' => 'c5' ),
'integrated_edit_field9' => array( 'location' => 'step2',
'cellId' => 'c6' ),
'integrated_edit_field10' => array( 'location' => 'step2',
'cellId' => 'c7' ),
'edit_field_label' => array( 'location' => 'step2',
'cellId' => 'c8' ),
'edit_field_tooltip' => array( 'location' => 'step2',
'cellId' => 'c8' ),
'integrated_edit_field1' => array( 'location' => 'step2',
'cellId' => 'c8' ),
'integrated_edit_field25' => array( 'location' => 'step2',
'cellId' => 'c10' ),
'integrated_edit_field' => array( 'location' => 'step2',
'cellId' => 'c12' ),
'integrated_edit_field8' => array( 'location' => 'step2',
'cellId' => 'c13' ) ),
'itemVisiblity' => array( 'expand_menu_button' => 2,
'expand_menu_button1' => 2,
'expand_button' => 5 ) ),
'itemsByType' => array( 'add_header' => array( 'add_header' ),
'add_message' => array( 'add_message' ),
'step_nav' => array( 'step_nav' ),
'next_step' => array( 'next_step' ),
'add_save' => array( 'add_save' ),
'add_back_list' => array( 'add_back_list' ),
'add_cancel' => array( 'add_cancel' ),
'integrated_edit_field' => array( 'integrated_edit_field17',
'integrated_edit_field',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field27',
'integrated_edit_field18',
'integrated_edit_field19',
'integrated_edit_field2',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field4',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field8',
'integrated_edit_field22',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field26',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field25' ),
'edit_field_label' => array( 'edit_field_label' ),
'edit_field_tooltip' => array( 'edit_field_tooltip' ),
'edit_field' => array( 'integrated_edit_field1' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'menu' => array( 'menu' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'expand_menu_button' => array( 'expand_menu_button',
'expand_menu_button1' ),
'collapse_button' => array( 'collapse_button' ),
'logo' => array( 'logo1' ),
'changepassword_link' => array( 'changepassword_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c6' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field14' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field15' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field17' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c1' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field16' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field27' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c11' => array( 'cols' => array( 0,
1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field18' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field19' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 5 ),
'step3' => array( 'cells' => array( 'c4' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field20' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field21' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 3 ),
'step2' => array( 'cells' => array( 'c8' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'edit_field_label',
'edit_field_tooltip',
'integrated_edit_field1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c1' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field22' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field23' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c10' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field25' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c11' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field24' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field26' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field10' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c12' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c13' => array( 'cols' => array( 1 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 6 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => true,
'multiStep' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array( array( 'id' => 'main',
'horizontal' => false ) ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'add',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'add',
'type' => 'add',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'add-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_message' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'step_nav' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'add-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'next_step',
'add_save',
'add_back_list',
'add_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'expand_menu_button1',
'collapse_button' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo1',
'expand_button' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'add-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c6' ),
array( 'cell' => 'c7' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ),
array( 'cell' => 'c3' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c11',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c8' ),
array( 'cell' => 'c9' ) ) ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array(  ) ),
'c' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field17' ) ),
'c6' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field14' ) ),
'c7' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field15' ) ),
'c1' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field16' ) ),
'c2' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field27' ) ),
'c8' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field18' ) ),
'c9' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field19' ) ),
'c11' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field2' ),
'useFullWidth' => true ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'step3' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c5',
'colspan' => 1 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c6' ),
array( 'cell' => 'c',
'colspan' => 1 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c8' ),
array( 'cell' => 'c9',
'colspan' => 1 ) ) ) ),
'cells' => array( 'c' => array( 'model' => 'c3',
'items' => array(  ) ),
'c4' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field5' ) ),
'c5' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field6' ) ),
'c6' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field4' ) ),
'c8' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field20' ) ),
'c9' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field21' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'step2' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c8' ),
array( 'cell' => 'c9' ) ) ),
array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c10' ),
array( 'cell' => 'c11' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c5' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c6' ),
array( 'cell' => 'c7' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c12' ),
array( 'cell' => 'c13' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field22' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field23' ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field24' ) ),
'c5' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field26' ) ),
'c6' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field9' ) ),
'c7' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field10' ) ),
'c8' => array( 'model' => 'c3',
'items' => array( 'edit_field_label',
'edit_field_tooltip',
'integrated_edit_field1' ) ),
'c9' => array( 'model' => 'c1',
'items' => array(  ) ),
'c10' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field25' ) ),
'c11' => array( 'model' => 'c1',
'items' => array(  ) ),
'c12' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field' ) ),
'c13' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field8' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'add_header' => array( 'type' => 'add_header',
'title' => array( 'page' => 'add',
'table' => 'concertacion_po',
'type' => 7 ) ),
'add_message' => array( 'type' => 'add_message' ),
'step_nav' => array( 'type' => 'step_nav' ),
'next_step' => array( 'type' => 'next_step',
'icon' => array( 'fa' => 'angle-double-right' ),
'buttonStyle' => 'info',
'buttonSize' => 'normal' ),
'add_save' => array( 'type' => 'add_save',
'buttonStyle' => 'success',
'buttonSize' => 'normal',
'label' => array( 'type' => 0,
'text' => 'Crear concertación' ) ),
'add_back_list' => array( 'type' => 'add_back_list' ),
'add_cancel' => array( 'type' => 'add_cancel' ),
'integrated_edit_field17' => array( 'field' => 'evaluado_email',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field' => array( 'field' => 'idEvaluado',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field14' => array( 'field' => 'evaluado_doc',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field15' => array( 'field' => 'evaluado_nombre',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field16' => array( 'field' => 'evaluado_cargo',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field27' => array( 'field' => 'evaluado_nombramiento',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field18' => array( 'field' => 'evaluado_dep_sup',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field19' => array( 'field' => 'evaluado_dep',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field2' => array( 'field' => 'id_comportamental_fk',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field5' => array( 'field' => 'periodo',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'periodo',
'table' => 'concertacion_po',
'type' => 3 ) ),
'integrated_edit_field6' => array( 'field' => 'fchCreacion',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field4' => array( 'field' => 'vigencia',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field20' => array( 'field' => 'evaluado_fechai_po',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field21' => array( 'field' => 'evaluado_fechaf_po',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field8' => array( 'field' => 'estado',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field22' => array( 'field' => 'evaluador_doc',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field23' => array( 'field' => 'evaluador_nombre',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field24' => array( 'field' => 'evaluador_cargo',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field26' => array( 'field' => 'evaluador_nombramiento',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field9' => array( 'field' => 'evaluador_dep_sup',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field10' => array( 'field' => 'evaluador_dep',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'edit_field_label' => array( 'type' => 'edit_field_label',
'field' => 'idEvaluador',
'separated' => true ),
'edit_field_tooltip' => array( 'type' => 'edit_field_tooltip',
'field' => 'idEvaluador',
'separated' => true ),
'integrated_edit_field1' => array( 'field' => 'idEvaluador',
'type' => 'edit_field',
'orientation' => 0,
'tooltip' => array( 'field' => 'idEvaluador',
'table' => null,
'type' => 4 ),
'joined' => false,
'separated' => true ),
'integrated_edit_field25' => array( 'field' => 'evaluador_email',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'menu' => array( 'type' => 'menu' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link',
'changepassword_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'logo1' => array( 'type' => 'logo' ),
'expand_menu_button1' => array( 'type' => 'expand_menu_button' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'steps' => array( array( 'location' => 'step3',
'label' => array( 'text' => 'Concertación',
'type' => 0 ) ),
array( 'location' => 'grid',
'label' => array( 'text' => 'Evaluado',
'type' => 0 ) ),
array( 'location' => 'step2',
'label' => array( 'text' => 'Evaluador',
'type' => 0 ) ) ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>