<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'id',
'idEvaluado',
'idEvaluador',
'vigencia',
'periodo',
'fchCreacion',
'fchEdefinitiva',
'estado',
'email_not_cierre',
'fecha_not_cierre',
'sys_user',
'evaluado_doc',
'evaluado_nombre',
'evaluado_cargo',
'evaluado_email',
'evaluado_dep_sup',
'evaluado_dep',
'evaluado_fechai_po',
'evaluado_fechaf_po',
'evaluador_doc',
'evaluador_nombre',
'evaluador_cargo',
'evaluador_email',
'evaluador_dep_sup',
'evaluador_dep',
'evaluador_nombramiento',
'evaluado_nombramiento',
'id_comportamental_fk',
'valor_programado',
'valor_comun',
'valor_jerarquico',
'valor_total' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'id' => array( 'import_field' ),
'idEvaluado' => array( 'import_field1' ),
'idEvaluador' => array( 'import_field2' ),
'vigencia' => array( 'import_field5' ),
'periodo' => array( 'import_field6' ),
'fchCreacion' => array( 'import_field7' ),
'fchEdefinitiva' => array( 'import_field8' ),
'estado' => array( 'import_field9' ),
'evaluador_dep_sup' => array( 'import_field10' ),
'evaluador_dep' => array( 'import_field11' ),
'email_not_cierre' => array( 'import_field12' ),
'fecha_not_cierre' => array( 'import_field13' ),
'sys_user' => array( 'import_field14' ),
'evaluado_doc' => array( 'import_field15' ),
'evaluado_nombre' => array( 'import_field16' ),
'evaluado_cargo' => array( 'import_field17' ),
'evaluado_email' => array( 'import_field18' ),
'evaluado_dep_sup' => array( 'import_field19' ),
'evaluado_dep' => array( 'import_field20' ),
'evaluado_fechai_po' => array( 'import_field21' ),
'evaluado_fechaf_po' => array( 'import_field22' ),
'evaluador_doc' => array( 'import_field23' ),
'evaluador_nombre' => array( 'import_field24' ),
'evaluador_cargo' => array( 'import_field25' ),
'evaluador_email' => array( 'import_field26' ),
'evaluador_nombramiento' => array( 'import_field27' ),
'evaluado_nombramiento' => array( 'import_field28' ),
'id_comportamental_fk' => array( 'import_field3' ),
'valor_programado' => array( 'import_field4' ),
'valor_comun' => array( 'import_field29' ),
'valor_jerarquico' => array( 'import_field30' ),
'valor_total' => array( 'import_field31' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field10',
'import_field11',
'import_field27',
'import_field28',
'import_field3',
'import_field4',
'import_field29',
'import_field30',
'import_field31' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field17' => 'grid',
'import_field18' => 'grid',
'import_field19' => 'grid',
'import_field20' => 'grid',
'import_field21' => 'grid',
'import_field22' => 'grid',
'import_field23' => 'grid',
'import_field24' => 'grid',
'import_field25' => 'grid',
'import_field26' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field27' => 'grid',
'import_field28' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field29' => 'grid',
'import_field30' => 'grid',
'import_field31' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field3',
'import_field4',
'import_field29',
'import_field30',
'import_field31' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field10',
'import_field11',
'import_field27',
'import_field28',
'import_field3',
'import_field4',
'import_field29',
'import_field30',
'import_field31' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'id',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'idEvaluado',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'idEvaluador',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'vigencia',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'periodo',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'fchCreacion',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'fchEdefinitiva',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'estado',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'evaluador_dep_sup',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'evaluador_dep',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'email_not_cierre',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'fecha_not_cierre',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'sys_user',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'evaluado_doc',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'evaluado_nombre',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'evaluado_cargo',
'type' => 'import_field' ),
'import_field18' => array( 'field' => 'evaluado_email',
'type' => 'import_field' ),
'import_field19' => array( 'field' => 'evaluado_dep_sup',
'type' => 'import_field' ),
'import_field20' => array( 'field' => 'evaluado_dep',
'type' => 'import_field' ),
'import_field21' => array( 'field' => 'evaluado_fechai_po',
'type' => 'import_field' ),
'import_field22' => array( 'field' => 'evaluado_fechaf_po',
'type' => 'import_field' ),
'import_field23' => array( 'field' => 'evaluador_doc',
'type' => 'import_field' ),
'import_field24' => array( 'field' => 'evaluador_nombre',
'type' => 'import_field' ),
'import_field25' => array( 'field' => 'evaluador_cargo',
'type' => 'import_field' ),
'import_field26' => array( 'field' => 'evaluador_email',
'type' => 'import_field' ),
'import_field27' => array( 'field' => 'evaluador_nombramiento',
'type' => 'import_field' ),
'import_field28' => array( 'field' => 'evaluado_nombramiento',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'id_comportamental_fk',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'valor_programado',
'type' => 'import_field' ),
'import_field29' => array( 'field' => 'valor_comun',
'type' => 'import_field' ),
'import_field30' => array( 'field' => 'valor_jerarquico',
'type' => 'import_field' ),
'import_field31' => array( 'field' => 'valor_total',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>