<?php
			$optionsArray = array( 'details' => array( 'compromisofuncional' => array( 'displayPreview' => 2,
'previewPageId' => '' ),
'comportamental_comun' => array( 'displayPreview' => 2,
'previewPageId' => '' ),
'comportamental_jerarquica' => array( 'displayPreview' => 2,
'previewPageId' => '' ) ),
'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 'idEvaluado',
'idEvaluador',
'vigencia',
'periodo',
'fchCreacion',
'estado',
'evaluador_dep_sup',
'evaluador_dep',
'evaluado_doc',
'evaluado_nombre',
'evaluado_cargo',
'evaluado_email',
'evaluado_dep_sup',
'evaluado_dep',
'evaluado_fechai_po',
'evaluado_fechaf_po',
'evaluador_doc',
'evaluador_nombre',
'evaluador_cargo',
'evaluador_email',
'evaluador_nombramiento',
'evaluado_nombramiento',
'id_comportamental_fk' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'updateOnEditFields' => array(  ),
'fieldItems' => array( 'idEvaluado' => array( 'integrated_edit_field' ),
'idEvaluador' => array( 'integrated_edit_field1' ),
'vigencia' => array( 'integrated_edit_field4' ),
'periodo' => array( 'integrated_edit_field5' ),
'fchCreacion' => array( 'integrated_edit_field6' ),
'estado' => array( 'integrated_edit_field8' ),
'evaluador_dep_sup' => array( 'integrated_edit_field9' ),
'evaluador_dep' => array( 'integrated_edit_field10' ),
'evaluado_doc' => array( 'integrated_edit_field14' ),
'evaluado_nombre' => array( 'integrated_edit_field15' ),
'evaluado_cargo' => array( 'integrated_edit_field16' ),
'evaluado_email' => array( 'integrated_edit_field17' ),
'evaluado_dep_sup' => array( 'integrated_edit_field18' ),
'evaluado_dep' => array( 'integrated_edit_field19' ),
'evaluado_fechai_po' => array( 'integrated_edit_field20' ),
'evaluado_fechaf_po' => array( 'integrated_edit_field21' ),
'evaluador_doc' => array( 'integrated_edit_field22' ),
'evaluador_nombre' => array( 'integrated_edit_field23' ),
'evaluador_cargo' => array( 'integrated_edit_field24' ),
'evaluador_email' => array( 'integrated_edit_field25' ),
'evaluador_nombramiento' => array( 'integrated_edit_field26' ),
'evaluado_nombramiento' => array( 'integrated_edit_field27' ),
'id_comportamental_fk' => array( 'integrated_edit_field2' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'edit_message',
'step_nav' ),
'below-grid' => array( 'next_step',
'edit_save',
'edit_back_list',
'edit_close',
'hamburger' ),
'top' => array( 'edit_header' ),
'grid' => array( 'integrated_edit_field17',
'integrated_edit_field',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field27',
'integrated_edit_field18',
'integrated_edit_field19',
'integrated_edit_field2' ),
'step2' => array( 'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field4',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field8' ),
'step3' => array( 'integrated_edit_field22',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field26',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field1',
'integrated_edit_field25' ) ),
'formXtTags' => array(  ),
'itemForms' => array( 'edit_message' => 'above-grid',
'step_nav' => 'above-grid',
'next_step' => 'below-grid',
'edit_save' => 'below-grid',
'edit_back_list' => 'below-grid',
'edit_close' => 'below-grid',
'hamburger' => 'below-grid',
'edit_header' => 'top',
'integrated_edit_field17' => 'grid',
'integrated_edit_field' => 'grid',
'integrated_edit_field14' => 'grid',
'integrated_edit_field15' => 'grid',
'integrated_edit_field16' => 'grid',
'integrated_edit_field27' => 'grid',
'integrated_edit_field18' => 'grid',
'integrated_edit_field19' => 'grid',
'integrated_edit_field2' => 'grid',
'integrated_edit_field5' => 'step2',
'integrated_edit_field6' => 'step2',
'integrated_edit_field4' => 'step2',
'integrated_edit_field20' => 'step2',
'integrated_edit_field21' => 'step2',
'integrated_edit_field8' => 'step2',
'integrated_edit_field22' => 'step3',
'integrated_edit_field23' => 'step3',
'integrated_edit_field24' => 'step3',
'integrated_edit_field26' => 'step3',
'integrated_edit_field9' => 'step3',
'integrated_edit_field10' => 'step3',
'integrated_edit_field1' => 'step3',
'integrated_edit_field25' => 'step3' ),
'itemLocations' => array( 'integrated_edit_field17' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'integrated_edit_field14' => array( 'location' => 'grid',
'cellId' => 'c6' ),
'integrated_edit_field15' => array( 'location' => 'grid',
'cellId' => 'c7' ),
'integrated_edit_field16' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_edit_field27' => array( 'location' => 'grid',
'cellId' => 'c2' ),
'integrated_edit_field18' => array( 'location' => 'grid',
'cellId' => 'c8' ),
'integrated_edit_field19' => array( 'location' => 'grid',
'cellId' => 'c9' ),
'integrated_edit_field2' => array( 'location' => 'grid',
'cellId' => 'c11' ),
'integrated_edit_field5' => array( 'location' => 'step2',
'cellId' => 'c4' ),
'integrated_edit_field6' => array( 'location' => 'step2',
'cellId' => 'c5' ),
'integrated_edit_field4' => array( 'location' => 'step2',
'cellId' => 'c6' ),
'integrated_edit_field20' => array( 'location' => 'step2',
'cellId' => 'c8' ),
'integrated_edit_field21' => array( 'location' => 'step2',
'cellId' => 'c9' ),
'integrated_edit_field8' => array( 'location' => 'step2',
'cellId' => 'c10' ),
'integrated_edit_field22' => array( 'location' => 'step3',
'cellId' => 'c1' ),
'integrated_edit_field23' => array( 'location' => 'step3',
'cellId' => 'c' ),
'integrated_edit_field24' => array( 'location' => 'step3',
'cellId' => 'c4' ),
'integrated_edit_field26' => array( 'location' => 'step3',
'cellId' => 'c5' ),
'integrated_edit_field9' => array( 'location' => 'step3',
'cellId' => 'c6' ),
'integrated_edit_field10' => array( 'location' => 'step3',
'cellId' => 'c7' ),
'integrated_edit_field1' => array( 'location' => 'step3',
'cellId' => 'c8' ),
'integrated_edit_field25' => array( 'location' => 'step3',
'cellId' => 'c10' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'edit_header' => array( 'edit_header' ),
'hamburger' => array( 'hamburger' ),
'edit_reset' => array( 'edit_reset' ),
'edit_message' => array( 'edit_message' ),
'edit_save' => array( 'edit_save' ),
'edit_back_list' => array( 'edit_back_list' ),
'edit_close' => array( 'edit_close' ),
'integrated_edit_field' => array( 'integrated_edit_field',
'integrated_edit_field1',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field17',
'integrated_edit_field18',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field22',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field27',
'integrated_edit_field2' ),
'next_step' => array( 'next_step' ),
'step_nav' => array( 'step_nav' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c4' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field14' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field15' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field17' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c1' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field16' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field27' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c11' => array( 'cols' => array( 0,
1 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field18' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 1 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field19' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 6 ),
'step2' => array( 'cells' => array( 'c4' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field20' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field21' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c10' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c11' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 4 ),
'step3' => array( 'cells' => array( 'c8' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c1' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field22' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field23' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c10' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field25' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c11' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field24' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field26' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field10' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 5 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'multiStep' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'edit',
'breadcrumb' => false,
'nextPrev' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'edit' => array( 'updateSelected' => false ) );
			$pageArray = array( 'id' => 'edit',
'type' => 'edit',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'edit-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_message' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'step_nav' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'edit-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'next_step',
'edit_save',
'edit_back_list',
'edit_close' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'hamburger' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'edit-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c5' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c6' ),
array( 'cell' => 'c7' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ),
array( 'cell' => 'c3' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c11',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c8' ),
array( 'cell' => 'c9' ) ) ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array(  ) ),
'c' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field17' ) ),
'c4' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field' ) ),
'c5' => array( 'model' => 'c3',
'items' => array(  ) ),
'c6' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field14' ) ),
'c7' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field15' ) ),
'c1' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field16' ) ),
'c2' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field27' ) ),
'c8' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field18' ) ),
'c9' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field19' ) ),
'c11' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field2' ),
'useFullWidth' => true ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'step2' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c5',
'colspan' => 1 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c6' ),
array( 'cell' => 'c',
'colspan' => 1 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c8' ),
array( 'cell' => 'c9',
'colspan' => 1 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c10' ),
array( 'cell' => 'c11',
'colspan' => 1 ) ) ) ),
'cells' => array( 'c' => array( 'model' => 'c3',
'items' => array(  ) ),
'c4' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field5' ) ),
'c5' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field6' ) ),
'c6' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field4' ) ),
'c8' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field20' ) ),
'c9' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field21' ) ),
'c10' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field8' ) ),
'c11' => array( 'model' => 'c3',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'step3' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c8' ),
array( 'cell' => 'c9' ) ) ),
array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c10' ),
array( 'cell' => 'c11' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c5' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c6' ),
array( 'cell' => 'c7' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field22' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field23' ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field24' ) ),
'c5' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field26' ) ),
'c6' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field9' ) ),
'c7' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field10' ) ),
'c8' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field1' ) ),
'c9' => array( 'model' => 'c1',
'items' => array(  ) ),
'c10' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field25' ) ),
'c11' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'edit_header' => array( 'type' => 'edit_header' ),
'hamburger' => array( 'type' => 'hamburger',
'items' => array( 'edit_reset' ) ),
'edit_reset' => array( 'type' => 'edit_reset' ),
'edit_message' => array( 'type' => 'edit_message' ),
'edit_save' => array( 'type' => 'edit_save' ),
'edit_back_list' => array( 'type' => 'edit_back_list' ),
'edit_close' => array( 'type' => 'edit_close' ),
'integrated_edit_field' => array( 'field' => 'idEvaluado',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field1' => array( 'field' => 'idEvaluador',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field4' => array( 'field' => 'vigencia',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field5' => array( 'field' => 'periodo',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'periodo',
'table' => 'concertacion_po',
'type' => 3 ),
'updateOnEdit' => false ),
'integrated_edit_field6' => array( 'field' => 'fchCreacion',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field8' => array( 'field' => 'estado',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field9' => array( 'field' => 'evaluador_dep_sup',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field10' => array( 'field' => 'evaluador_dep',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field14' => array( 'field' => 'evaluado_doc',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field15' => array( 'field' => 'evaluado_nombre',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field16' => array( 'field' => 'evaluado_cargo',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field17' => array( 'field' => 'evaluado_email',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field18' => array( 'field' => 'evaluado_dep_sup',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field19' => array( 'field' => 'evaluado_dep',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field20' => array( 'field' => 'evaluado_fechai_po',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field21' => array( 'field' => 'evaluado_fechaf_po',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field22' => array( 'field' => 'evaluador_doc',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field23' => array( 'field' => 'evaluador_nombre',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field24' => array( 'field' => 'evaluador_cargo',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field25' => array( 'field' => 'evaluador_email',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field26' => array( 'field' => 'evaluador_nombramiento',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field27' => array( 'field' => 'evaluado_nombramiento',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'next_step' => array( 'type' => 'next_step' ),
'step_nav' => array( 'type' => 'step_nav' ),
'integrated_edit_field2' => array( 'field' => 'id_comportamental_fk',
'type' => 'integrated_edit_field',
'orientation' => 0 ) ),
'dbProps' => array(  ),
'steps' => array( array( 'location' => 'step2',
'label' => array( 'text' => 'Concertación',
'type' => 0 ) ),
array( 'location' => 'grid',
'label' => array( 'text' => 'Evaluado',
'type' => 0 ) ),
array( 'location' => 'step3',
'label' => array( 'text' => 'Evaluador',
'type' => 0 ) ) ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>