<?php
			$optionsArray = array( 'list' => array( 'inlineAdd' => false,
'detailsAdd' => false,
'inlineEdit' => false,
'spreadsheetMode' => false,
'reorderRows' => false,
'addToBottom' => false,
'delete' => true,
'updateSelected' => false,
'addInPopup' => true,
'editInPopup' => true,
'viewInPopup' => false,
'clickSort' => true,
'sortDropdown' => false,
'showHideFields' => false,
'reorderFields' => false,
'hideNumberOfRecords' => false ),
'allDetails' => array( 'linkType' => 0 ),
'details' => array( 'compromisofuncional_2' => array( 'displayPreview' => 1,
'previewPageId' => 'list',
'showCount' => true,
'hideEmptyChild' => false,
'hideEmptyPreview' => false,
'showProceedLink' => true,
'printDetails' => true ),
'comportamental_comun_2' => array( 'displayPreview' => 1,
'previewPageId' => 'list',
'showCount' => true,
'hideEmptyChild' => false,
'hideEmptyPreview' => false,
'showProceedLink' => true,
'printDetails' => true ),
'comportamental_jerarquica_2' => array( 'displayPreview' => 1,
'previewPageId' => 'list',
'showCount' => true,
'hideEmptyChild' => false,
'hideEmptyPreview' => false,
'showProceedLink' => true,
'printDetails' => true ) ),
'listSearch' => array( 'alwaysOnPanelFields' => array(  ),
'searchPanel' => true,
'fixedSearchPanel' => false,
'simpleSearchOptions' => false,
'searchSaving' => false ),
'totals' => array( 'id' => array( 'totalsType' => '' ),
'idEvaluado' => array( 'totalsType' => '' ),
'idEvaluador' => array( 'totalsType' => '' ),
'IdEvaluador_c' => array( 'totalsType' => '' ),
'IdEvaluador_d' => array( 'totalsType' => '' ),
'vigencia' => array( 'totalsType' => '' ),
'periodo' => array( 'totalsType' => '' ),
'fchCreacion' => array( 'totalsType' => '' ),
'fchEdefinitiva' => array( 'totalsType' => '' ),
'estado' => array( 'totalsType' => '' ),
'email_not_cierre' => array( 'totalsType' => '' ),
'fecha_not_cierre' => array( 'totalsType' => '' ),
'sys_user' => array( 'totalsType' => '' ),
'evaluado_doc' => array( 'totalsType' => '' ),
'evaluado_nombre' => array( 'totalsType' => '' ),
'evaluado_cargo' => array( 'totalsType' => '' ),
'evaluado_email' => array( 'totalsType' => '' ),
'evaluado_dep_sup' => array( 'totalsType' => '' ),
'evaluado_dep' => array( 'totalsType' => '' ),
'evaluado_fechai_po' => array( 'totalsType' => '' ),
'evaluado_fechaf_po' => array( 'totalsType' => '' ),
'evaluador_doc' => array( 'totalsType' => '' ),
'evaluador_nombre' => array( 'totalsType' => '' ),
'evaluador_cargo' => array( 'totalsType' => '' ),
'evaluador_email' => array( 'totalsType' => '' ),
'evaluador_dep_sup' => array( 'totalsType' => '' ),
'evaluador_dep' => array( 'totalsType' => '' ),
'evaluador_nombramiento' => array( 'totalsType' => '' ),
'evaluado_nombramiento' => array( 'totalsType' => '' ),
'id_comportamental_fk' => array( 'totalsType' => '' ),
'valor_programado' => array( 'totalsType' => '' ),
'valor_comun' => array( 'totalsType' => '' ),
'valor_jerarquico' => array( 'totalsType' => '' ),
'valor_total' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'id',
'evaluado_nombre',
'evaluador_nombre',
'evaluado_fechai_po',
'vigencia',
'evaluado_doc',
'evaluador_dep',
'evaluado_fechaf_po',
'fchCreacion',
'evaluado_cargo',
'evaluador_cargo',
'estado' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array( 'evaluador_dep',
'evaluador_cargo',
'evaluador_nombre',
'evaluado_fechaf_po',
'evaluado_fechai_po',
'evaluado_cargo',
'evaluado_nombre',
'evaluado_doc',
'vigencia',
'id',
'fchCreacion',
'estado' ),
'filterFields' => array(  ),
'inlineAddFields' => array(  ),
'inlineEditFields' => array(  ),
'fieldItems' => array( 'id' => array( 'simple_grid_field',
'simple_grid_field1' ),
'vigencia' => array( 'simple_grid_field5',
'simple_grid_field6' ),
'fchCreacion' => array( 'simple_grid_field7',
'simple_grid_field8' ),
'estado' => array( 'simple_grid_field9',
'simple_grid_field10' ),
'evaluado_doc' => array( 'simple_grid_field15',
'simple_grid_field17' ),
'evaluado_nombre' => array( 'simple_grid_field16',
'simple_grid_field18' ),
'evaluado_fechai_po' => array( 'simple_grid_field21',
'simple_grid_field23' ),
'evaluado_fechaf_po' => array( 'simple_grid_field22',
'simple_grid_field26' ),
'evaluador_nombre' => array( 'simple_grid_field24',
'simple_grid_field27' ),
'evaluador_cargo' => array( 'simple_grid_field25',
'simple_grid_field28' ),
'evaluado_cargo' => array( 'grid_field',
'grid_field_label' ),
'evaluador_dep' => array( 'grid_field1',
'grid_field_label1' ) ),
'hideEmptyFields' => array(  ),
'fieldFilterFields' => array(  ) ),
'pageLinks' => array( 'edit' => true,
'add' => true,
'view' => true,
'print' => true ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'add',
'delete',
'details_found',
'page_size',
'print_panel',
'text' ),
'below-grid' => array( 'pagination' ),
'left' => array( 'logo',
'expand_button',
'menu',
'search_panel' ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb',
'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'grid' => array( 'custom_button_container',
'grid_checkbox',
'grid_view',
'grid_alldetails_link',
'grid_details_link',
'grid_details_link1',
'grid_details_link2',
'details_preview',
'details_preview1',
'details_preview2',
'simple_grid_field1',
'simple_grid_field',
'simple_grid_field6',
'simple_grid_field5',
'simple_grid_field8',
'simple_grid_field7',
'simple_grid_field23',
'simple_grid_field21',
'simple_grid_field26',
'simple_grid_field22',
'simple_grid_field10',
'simple_grid_field9',
'simple_grid_field18',
'simple_grid_field16',
'simple_grid_field17',
'simple_grid_field15',
'grid_field_label',
'grid_field',
'simple_grid_field27',
'simple_grid_field24',
'grid_field_label1',
'grid_field1',
'simple_grid_field28',
'simple_grid_field25' ),
'top' => array(  ) ),
'formXtTags' => array( 'below-grid' => array( 'pagination' ),
'top' => array(  ) ),
'itemForms' => array( 'add' => 'above-grid',
'delete' => 'above-grid',
'details_found' => 'above-grid',
'page_size' => 'above-grid',
'print_panel' => 'above-grid',
'text' => 'above-grid',
'pagination' => 'below-grid',
'logo' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'search_panel' => 'left',
'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'breadcrumb' => 'supertop',
'simple_search' => 'supertop',
'list_options' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'custom_button_container' => 'grid',
'grid_checkbox' => 'grid',
'grid_view' => 'grid',
'grid_alldetails_link' => 'grid',
'grid_details_link' => 'grid',
'grid_details_link1' => 'grid',
'grid_details_link2' => 'grid',
'details_preview' => 'grid',
'details_preview1' => 'grid',
'details_preview2' => 'grid',
'simple_grid_field1' => 'grid',
'simple_grid_field' => 'grid',
'simple_grid_field6' => 'grid',
'simple_grid_field5' => 'grid',
'simple_grid_field8' => 'grid',
'simple_grid_field7' => 'grid',
'simple_grid_field23' => 'grid',
'simple_grid_field21' => 'grid',
'simple_grid_field26' => 'grid',
'simple_grid_field22' => 'grid',
'simple_grid_field10' => 'grid',
'simple_grid_field9' => 'grid',
'simple_grid_field18' => 'grid',
'simple_grid_field16' => 'grid',
'simple_grid_field17' => 'grid',
'simple_grid_field15' => 'grid',
'grid_field_label' => 'grid',
'grid_field' => 'grid',
'simple_grid_field27' => 'grid',
'simple_grid_field24' => 'grid',
'grid_field_label1' => 'grid',
'grid_field1' => 'grid',
'simple_grid_field28' => 'grid',
'simple_grid_field25' => 'grid' ),
'itemLocations' => array( 'custom_button_container' => array( 'location' => 'grid',
'cellId' => 'cell_top' ),
'grid_checkbox' => array( 'location' => 'grid',
'cellId' => 'cell_top' ),
'grid_view' => array( 'location' => 'grid',
'cellId' => 'cell_top' ),
'grid_alldetails_link' => array( 'location' => 'grid',
'cellId' => 'cell_top' ),
'grid_details_link' => array( 'location' => 'grid',
'cellId' => 'cell_top' ),
'grid_details_link1' => array( 'location' => 'grid',
'cellId' => 'cell_top' ),
'grid_details_link2' => array( 'location' => 'grid',
'cellId' => 'cell_top' ),
'details_preview' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview' ),
'details_preview1' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview' ),
'details_preview2' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview' ),
'simple_grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_label' ),
'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_label1' ),
'simple_grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'simple_grid_field8' => array( 'location' => 'grid',
'cellId' => 'cell_label2' ),
'simple_grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'simple_grid_field23' => array( 'location' => 'grid',
'cellId' => 'cell_label3' ),
'simple_grid_field21' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'simple_grid_field26' => array( 'location' => 'grid',
'cellId' => 'cell_label4' ),
'simple_grid_field22' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'simple_grid_field10' => array( 'location' => 'grid',
'cellId' => 'cell_label5' ),
'simple_grid_field9' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'simple_grid_field18' => array( 'location' => 'grid',
'cellId' => 'cell_field12' ),
'simple_grid_field16' => array( 'location' => 'grid',
'cellId' => 'cell_field13' ),
'simple_grid_field17' => array( 'location' => 'grid',
'cellId' => 'cell_field14' ),
'simple_grid_field15' => array( 'location' => 'grid',
'cellId' => 'cell_field15' ),
'grid_field_label' => array( 'location' => 'grid',
'cellId' => 'cell_field16' ),
'grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field17' ),
'simple_grid_field27' => array( 'location' => 'grid',
'cellId' => 'cell_field18' ),
'simple_grid_field24' => array( 'location' => 'grid',
'cellId' => 'cell_field19' ),
'grid_field_label1' => array( 'location' => 'grid',
'cellId' => 'cell_field20' ),
'grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field21' ),
'simple_grid_field28' => array( 'location' => 'grid',
'cellId' => 'cell_field22' ),
'simple_grid_field25' => array( 'location' => 'grid',
'cellId' => 'cell_field23' ) ),
'itemVisiblity' => array( 'breadcrumb' => 5,
'expand_menu_button' => 2,
'print_panel' => 5,
'expand_button' => 5 ) ),
'itemsByType' => array( 'page_size' => array( 'page_size' ),
'details_found' => array( 'details_found' ),
'breadcrumb' => array( 'breadcrumb' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'pagination' => array( 'pagination' ),
'search_panel' => array( 'search_panel' ),
'list_options' => array( 'list_options' ),
'show_search_panel' => array( 'show_search_panel' ),
'hide_search_panel' => array( 'hide_search_panel' ),
'search_panel_field' => array( 'search_panel_field3',
'search_panel_field4',
'search_panel_field8',
'search_panel_field9',
'search_panel_field13',
'search_panel_field15',
'search_panel_field16',
'search_panel_field17',
'search_panel_field21',
'search_panel_field22',
'search_panel_field24',
'search_panel_field25' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'add' => array( 'add' ),
'grid_edit' => array( 'grid_edit' ),
'grid_view' => array( 'grid_view' ),
'print_panel' => array( 'print_panel' ),
'print_scope' => array( 'print_scope' ),
'print_button' => array( 'print_button' ),
'print_records' => array( 'print_records' ),
'grid_checkbox' => array( 'grid_checkbox' ),
'grid_checkbox_head' => array( 'grid_checkbox_head' ),
'export' => array( 'export' ),
'-' => array( '-',
'-1',
'-2',
'-3' ),
'export_selected' => array( 'export_selected' ),
'import' => array( 'import' ),
'delete' => array( 'delete' ),
'delete_selected' => array( 'delete_selected' ),
'advsearch_link' => array( 'advsearch_link' ),
'grid_field' => array( 'simple_grid_field',
'simple_grid_field5',
'simple_grid_field7',
'simple_grid_field9',
'simple_grid_field15',
'simple_grid_field16',
'simple_grid_field21',
'simple_grid_field22',
'simple_grid_field24',
'simple_grid_field25',
'grid_field',
'grid_field1' ),
'username_button' => array( 'username_button' ),
'changepassword_link' => array( 'changepassword_link' ),
'loginform_login' => array( 'loginform_login' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'print_details' => array( 'print_details' ),
'details_preview' => array( 'details_preview',
'details_preview1',
'details_preview2' ),
'grid_alldetails_link' => array( 'grid_alldetails_link' ),
'grid_details_link' => array( 'grid_details_link',
'grid_details_link1',
'grid_details_link2' ),
'grid_field_label' => array( 'simple_grid_field1',
'simple_grid_field6',
'simple_grid_field8',
'simple_grid_field17',
'simple_grid_field18',
'simple_grid_field23',
'simple_grid_field26',
'simple_grid_field27',
'simple_grid_field28',
'simple_grid_field10',
'grid_field_label',
'grid_field_label1' ),
'custom_button_container' => array( 'custom_button_container' ),
'custom_button' => array( 'custom_button' ),
'text' => array( 'text' ),
'adminarea_link' => array( 'adminarea_link' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'cell_top' => array( 'cols' => array( 0,
1,
2,
3,
4,
5 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'cell_label' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'id_fieldcolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label1' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'vigencia_fieldheadercolumn' ),
'items' => array( 'simple_grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'vigencia_fieldcolumn' ),
'items' => array( 'simple_grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label2' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'fchCreacion_fieldheadercolumn' ),
'items' => array( 'simple_grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array( 'fchCreacion_fieldcolumn' ),
'items' => array( 'simple_grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field12' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array( 'evaluado_nombre_fieldheadercolumn' ),
'items' => array( 'simple_grid_field18' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field13' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array( 'evaluado_nombre_fieldcolumn' ),
'items' => array( 'simple_grid_field16' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field14' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array( 'evaluado_doc_fieldheadercolumn' ),
'items' => array( 'simple_grid_field17' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field15' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array( 'evaluado_doc_fieldcolumn' ),
'items' => array( 'simple_grid_field15' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field16' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array( 'evaluado_cargo_fieldheadercolumn' ),
'items' => array( 'grid_field_label' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field17' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array( 'evaluado_cargo_fieldcolumn' ),
'items' => array( 'grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field18' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array( 'evaluador_nombre_fieldheadercolumn' ),
'items' => array( 'simple_grid_field27' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field19' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array( 'evaluador_nombre_fieldcolumn' ),
'items' => array( 'simple_grid_field24' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field20' => array( 'cols' => array( 2 ),
'rows' => array( 3 ),
'tags' => array( 'evaluador_dep_fieldheadercolumn' ),
'items' => array( 'grid_field_label1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field21' => array( 'cols' => array( 3 ),
'rows' => array( 3 ),
'tags' => array( 'evaluador_dep_fieldcolumn' ),
'items' => array( 'grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field22' => array( 'cols' => array( 4 ),
'rows' => array( 3 ),
'tags' => array( 'evaluador_cargo_fieldheadercolumn' ),
'items' => array( 'simple_grid_field28' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field23' => array( 'cols' => array( 5 ),
'rows' => array( 3 ),
'tags' => array( 'evaluador_cargo_fieldcolumn' ),
'items' => array( 'simple_grid_field25' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label3' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array( 'evaluado_fechai_po_fieldheadercolumn' ),
'items' => array( 'simple_grid_field23' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array( 'evaluado_fechai_po_fieldcolumn' ),
'items' => array( 'simple_grid_field21' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label4' => array( 'cols' => array( 2 ),
'rows' => array( 4 ),
'tags' => array( 'evaluado_fechaf_po_fieldheadercolumn' ),
'items' => array( 'simple_grid_field26' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 3 ),
'rows' => array( 4 ),
'tags' => array( 'evaluado_fechaf_po_fieldcolumn' ),
'items' => array( 'simple_grid_field22' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label5' => array( 'cols' => array( 4 ),
'rows' => array( 4 ),
'tags' => array( 'estado_fieldheadercolumn' ),
'items' => array( 'simple_grid_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 4 ),
'tags' => array( 'estado_fieldcolumn' ),
'items' => array( 'simple_grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_dpreview' => array( 'cols' => array( 0,
1,
2,
3,
4,
5 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'details_preview',
'details_preview1',
'details_preview2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 6,
'height' => 6 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array( 'details_found' => array( 'tag' => 'DISPLAYING',
'type' => 2 ) ) ),
'gridType' => 2,
'recsPerRow' => 1,
'hasCustomButtons' => true,
'customButtons' => array( 'BtnBackBorradores' ),
'hasNotifications' => false,
'menus' => array( array( 'id' => 'main',
'horizontal' => false ) ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'list',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array( 'BtnBackBorradores' ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'list',
'type' => 'list',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'list-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c3',
'colspan' => 2 ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add',
'delete' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'details_found',
'page_size',
'print_panel' ) ),
'c3' => array( 'model' => 'c3',
'items' => array( 'text' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'list-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'pagination' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo',
'expand_button' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu',
'search_panel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'list_options',
'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'columns-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'cell_top',
'colspan' => 6 ) ),
'section' => 'head' ),
array( 'cells' => array( array( 'cell' => 'cell_label' ),
array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_label1' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_label2' ),
array( 'cell' => 'cell_field2' ) ),
'section' => 'body' ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field12' ),
array( 'cell' => 'cell_field13' ),
array( 'cell' => 'cell_field14' ),
array( 'cell' => 'cell_field15' ),
array( 'cell' => 'cell_field16' ),
array( 'cell' => 'cell_field17' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field18' ),
array( 'cell' => 'cell_field19' ),
array( 'cell' => 'cell_field20' ),
array( 'cell' => 'cell_field21' ),
array( 'cell' => 'cell_field22' ),
array( 'cell' => 'cell_field23' ) ) ),
array( 'cells' => array( array( 'cell' => 'cell_label3' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_label4' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_label5' ),
array( 'cell' => 'cell_field5' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_dpreview',
'colspan' => 6 ) ),
'section' => 'foot' ) ),
'cells' => array( 'cell_top' => array( 'model' => 'cell_top',
'items' => array( 'custom_button_container',
'grid_checkbox',
'grid_view',
'grid_alldetails_link',
'grid_details_link',
'grid_details_link1',
'grid_details_link2' ) ),
'cell_dpreview' => array( 'model' => 'cell_dpreview',
'items' => array( 'details_preview',
'details_preview1',
'details_preview2' ) ),
'cell_label' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field1' ),
'field' => 'id',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field' ),
'field' => 'id',
'columnName' => 'field' ),
'cell_label1' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field6' ),
'field' => 'vigencia',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field5' ),
'field' => 'vigencia',
'columnName' => 'field' ),
'cell_label2' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field8' ),
'field' => 'fchCreacion',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field7' ),
'field' => 'fchCreacion',
'columnName' => 'field' ),
'cell_label3' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field23' ),
'field' => 'evaluado_fechai_po',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field21' ),
'field' => 'evaluado_fechai_po',
'columnName' => 'field' ),
'cell_label4' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field26' ),
'field' => 'evaluado_fechaf_po',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field22' ),
'field' => 'evaluado_fechaf_po',
'columnName' => 'field' ),
'cell_label5' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field10' ),
'field' => 'estado',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field9' ),
'field' => 'estado',
'columnName' => 'field' ),
'cell_field12' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field18' ),
'field' => 'evaluado_nombre',
'columnName' => 'field' ),
'cell_field13' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field16' ),
'field' => 'evaluado_nombre',
'columnName' => 'field' ),
'cell_field14' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field17' ),
'field' => 'evaluado_doc',
'columnName' => 'field' ),
'cell_field15' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field15' ),
'field' => 'evaluado_doc',
'columnName' => 'field' ),
'cell_field16' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label' ),
'field' => 'evaluado_cargo',
'columnName' => 'field' ),
'cell_field17' => array( 'model' => 'cell_field',
'items' => array( 'grid_field' ),
'field' => 'evaluado_cargo',
'columnName' => 'field' ),
'cell_field18' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field27' ),
'field' => 'evaluador_nombre',
'columnName' => 'field' ),
'cell_field19' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field24' ),
'field' => 'evaluador_nombre',
'columnName' => 'field' ),
'cell_field20' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label1' ),
'field' => 'evaluador_dep',
'columnName' => 'field' ),
'cell_field21' => array( 'model' => 'cell_field',
'items' => array( 'grid_field1' ),
'field' => 'evaluador_dep',
'columnName' => 'field' ),
'cell_field22' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field28' ),
'field' => 'evaluador_cargo',
'columnName' => 'field' ),
'cell_field23' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field25' ),
'field' => 'evaluador_cargo',
'columnName' => 'field' ) ),
'deferredItems' => array( 'grid_checkbox_head' ),
'buildType' => 2,
'columnCount' => 3 ),
'top' => array( 'modelId' => 'list-sidebar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'page_size' => array( 'type' => 'page_size' ),
'details_found' => array( 'type' => 'details_found' ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'simple_search' => array( 'type' => 'simple_search' ),
'pagination' => array( 'type' => 'pagination' ),
'search_panel' => array( 'type' => 'search_panel',
'items' => array( 'search_panel_field8',
'search_panel_field25',
'search_panel_field24',
'search_panel_field22',
'search_panel_field21',
'search_panel_field17',
'search_panel_field16',
'search_panel_field15',
'search_panel_field13',
'search_panel_field9',
'search_panel_field4',
'search_panel_field3' ) ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'export_selected',
'delete_selected',
'-3',
'advsearch_link',
'show_search_panel',
'hide_search_panel',
'-1',
'export',
'-2',
'import' ) ),
'show_search_panel' => array( 'type' => 'show_search_panel' ),
'hide_search_panel' => array( 'type' => 'hide_search_panel' ),
'search_panel_field3' => array( 'field' => 'estado',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field4' => array( 'field' => 'fchCreacion',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field8' => array( 'field' => 'evaluador_dep',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field9' => array( 'field' => 'id',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field13' => array( 'field' => 'vigencia',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'add' => array( 'type' => 'add',
'popup' => true ),
'grid_edit' => array( 'type' => 'grid_edit',
'popup' => true,
'label' => array( 'text' => 'Notificar al evaluador',
'type' => 0 ),
'buttonStyle' => 'success',
'buttonSize' => 'normal',
'icon' => array( 'fa' => 'send-o' ) ),
'grid_view' => array( 'type' => 'grid_view',
'popup' => false ),
'print_panel' => array( 'type' => 'print_panel',
'items' => array( 'print_scope',
'print_details',
'print_records',
'print_button' ) ),
'print_scope' => array( 'type' => 'print_scope' ),
'print_button' => array( 'type' => 'print_button' ),
'print_records' => array( 'type' => 'print_records' ),
'grid_checkbox' => array( 'type' => 'grid_checkbox' ),
'grid_checkbox_head' => array( 'type' => 'grid_checkbox_head' ),
'export' => array( 'type' => 'export' ),
'-' => array( 'type' => '-' ),
'export_selected' => array( 'type' => 'export_selected' ),
'-1' => array( 'type' => '-' ),
'import' => array( 'type' => 'import' ),
'-2' => array( 'type' => '-' ),
'delete' => array( 'type' => 'delete' ),
'delete_selected' => array( 'type' => 'delete_selected' ),
'advsearch_link' => array( 'type' => 'advsearch_link' ),
'-3' => array( 'type' => '-' ),
'simple_grid_field' => array( 'field' => 'id',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field5' => array( 'field' => 'vigencia',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field7' => array( 'field' => 'fchCreacion',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field9' => array( 'field' => 'estado',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link',
'changepassword_link' ) ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'simple_grid_field15' => array( 'field' => 'evaluado_doc',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'search_panel_field15' => array( 'field' => 'evaluado_doc',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'simple_grid_field16' => array( 'field' => 'evaluado_nombre',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'search_panel_field16' => array( 'field' => 'evaluado_nombre',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field17' => array( 'field' => 'evaluado_cargo',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'simple_grid_field21' => array( 'field' => 'evaluado_fechai_po',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'search_panel_field21' => array( 'field' => 'evaluado_fechai_po',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'simple_grid_field22' => array( 'field' => 'evaluado_fechaf_po',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'search_panel_field22' => array( 'field' => 'evaluado_fechaf_po',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'simple_grid_field24' => array( 'field' => 'evaluador_nombre',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'search_panel_field24' => array( 'field' => 'evaluador_nombre',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'simple_grid_field25' => array( 'field' => 'evaluador_cargo',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'search_panel_field25' => array( 'field' => 'evaluador_cargo',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'print_details' => array( 'type' => 'print_details',
'tables' => array( 'compromisofuncional_2' => true,
'comportamental_comun_2' => true,
'comportamental_jerarquica_2' => true ) ),
'details_preview' => array( 'type' => 'details_preview',
'table' => 'compromisofuncional_2',
'items' => array(  ),
'popup' => false,
'hideEmptyPreview' => false,
'proceedLink' => true,
'pageId' => 'list' ),
'grid_alldetails_link' => array( 'type' => 'grid_alldetails_link' ),
'grid_details_link' => array( 'type' => 'grid_details_link',
'table' => 'compromisofuncional_2',
'badge' => true,
'hideIfNone' => false,
'showCount' => true ),
'details_preview1' => array( 'type' => 'details_preview',
'table' => 'comportamental_comun_2',
'items' => array(  ),
'popup' => false,
'hideEmptyPreview' => false,
'proceedLink' => true,
'pageId' => 'list' ),
'grid_details_link1' => array( 'type' => 'grid_details_link',
'table' => 'comportamental_comun_2',
'badge' => true,
'showCount' => true,
'hideIfNone' => false ),
'details_preview2' => array( 'type' => 'details_preview',
'table' => 'comportamental_jerarquica_2',
'items' => array(  ),
'popup' => false,
'hideEmptyPreview' => false,
'proceedLink' => true,
'pageId' => 'list' ),
'grid_details_link2' => array( 'type' => 'grid_details_link',
'table' => 'comportamental_jerarquica_2',
'badge' => true,
'showCount' => true,
'hideIfNone' => false ),
'simple_grid_field1' => array( 'type' => 'grid_field_label',
'field' => 'id',
'clickSort' => true ),
'simple_grid_field6' => array( 'type' => 'grid_field_label',
'field' => 'vigencia',
'clickSort' => true ),
'simple_grid_field8' => array( 'type' => 'grid_field_label',
'field' => 'fchCreacion',
'clickSort' => true ),
'simple_grid_field17' => array( 'type' => 'grid_field_label',
'field' => 'evaluado_doc',
'clickSort' => true ),
'simple_grid_field18' => array( 'type' => 'grid_field_label',
'field' => 'evaluado_nombre',
'clickSort' => true ),
'simple_grid_field23' => array( 'type' => 'grid_field_label',
'field' => 'evaluado_fechai_po',
'clickSort' => true ),
'simple_grid_field26' => array( 'type' => 'grid_field_label',
'field' => 'evaluado_fechaf_po',
'clickSort' => true ),
'simple_grid_field27' => array( 'type' => 'grid_field_label',
'field' => 'evaluador_nombre',
'clickSort' => true ),
'simple_grid_field28' => array( 'type' => 'grid_field_label',
'field' => 'evaluador_cargo',
'clickSort' => true ),
'simple_grid_field10' => array( 'type' => 'grid_field_label',
'field' => 'estado',
'clickSort' => true ),
'custom_button_container' => array( 'type' => 'custom_button_container',
'items' => array( 'grid_edit',
'custom_button' ),
'icon' => array( 'fa' => 'angle-double-down' ),
'label' => array( 'type' => 0,
'text' => 'Acción' ),
'buttonStyle' => 'info',
'buttonSize' => 'normal' ),
'custom_button' => array( 'eventId' => 'BtnBackBorradores',
'label' => array( 'text' => 'Regresar y corregir',
'type' => 0 ),
'type' => 'custom_button',
'icon' => array( 'fa' => 'reply' ) ),
'grid_field' => array( 'field' => 'evaluado_cargo',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label' => array( 'type' => 'grid_field_label',
'field' => 'evaluado_cargo' ),
'grid_field1' => array( 'field' => 'evaluador_dep',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label1' => array( 'type' => 'grid_field_label',
'field' => 'evaluador_dep' ),
'text' => array( 'type' => 'text',
'label' => array( 'text' => '<div class="alert alert-warning" role="alert">
<p>Clic en el botón  <strong>"<em>Acción</em>"</strong> y seleccione la opción deseada para continuar </p></div>',
'type' => 0 ),
'editedByRte' => false ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'spreadsheetGrid' => false,
'version' => 14,
'reorderRows' => false,
'reorderRowsField' => '',
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>