<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => false ),
'details' => array( 'compromisofuncional_2' => array( 'displayPreview' => 2,
'previewPageId' => '' ),
'comportamental_comun_2' => array( 'displayPreview' => 2,
'previewPageId' => '' ),
'comportamental_jerarquica_2' => array( 'displayPreview' => 2,
'previewPageId' => '' ) ),
'fields' => array( 'gridFields' => array( 'id',
'evaluado_nombre',
'evaluado_email',
'evaluado_fechaf_po',
'evaluador_email',
'estado',
'evaluado_doc',
'vigencia',
'evaluador_doc',
'evaluador_nombre',
'evaluado_fechai_po',
'fchCreacion' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'id' => array( 'integrated_edit_field' ),
'evaluado_nombre' => array( 'integrated_edit_field15' ),
'evaluado_email' => array( 'integrated_edit_field17' ),
'evaluado_fechaf_po' => array( 'integrated_edit_field21' ),
'evaluador_email' => array( 'integrated_edit_field25' ),
'estado' => array( 'integrated_edit_field8' ),
'evaluado_doc' => array( 'integrated_edit_field14' ),
'vigencia' => array( 'integrated_edit_field4' ),
'evaluador_doc' => array( 'integrated_edit_field1' ),
'evaluador_nombre' => array( 'integrated_edit_field23' ),
'evaluado_fechai_po' => array( 'integrated_edit_field20' ),
'fchCreacion' => array( 'integrated_edit_field6' ) ) ),
'pageLinks' => array( 'edit' => true,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array(  ),
'below-grid' => array( 'view_back_list',
'view_close',
'hamburger' ),
'top' => array( 'view_header' ),
'grid' => array( 'text',
'integrated_edit_field8',
'integrated_edit_field15',
'integrated_edit_field14',
'integrated_edit_field',
'integrated_edit_field4',
'integrated_edit_field1',
'integrated_edit_field23',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field6',
'integrated_edit_field17',
'integrated_edit_field25' ) ),
'formXtTags' => array( 'above-grid' => array(  ) ),
'itemForms' => array( 'view_back_list' => 'below-grid',
'view_close' => 'below-grid',
'hamburger' => 'below-grid',
'view_header' => 'top',
'text' => 'grid',
'integrated_edit_field8' => 'grid',
'integrated_edit_field15' => 'grid',
'integrated_edit_field14' => 'grid',
'integrated_edit_field' => 'grid',
'integrated_edit_field4' => 'grid',
'integrated_edit_field1' => 'grid',
'integrated_edit_field23' => 'grid',
'integrated_edit_field20' => 'grid',
'integrated_edit_field21' => 'grid',
'integrated_edit_field6' => 'grid',
'integrated_edit_field17' => 'grid',
'integrated_edit_field25' => 'grid' ),
'itemLocations' => array( 'text' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field8' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'integrated_edit_field15' => array( 'location' => 'grid',
'cellId' => 'c6' ),
'integrated_edit_field14' => array( 'location' => 'grid',
'cellId' => 'c7' ),
'integrated_edit_field' => array( 'location' => 'grid',
'cellId' => 'c8' ),
'integrated_edit_field4' => array( 'location' => 'grid',
'cellId' => 'c9' ),
'integrated_edit_field1' => array( 'location' => 'grid',
'cellId' => 'c11' ),
'integrated_edit_field23' => array( 'location' => 'grid',
'cellId' => 'c10' ),
'integrated_edit_field20' => array( 'location' => 'grid',
'cellId' => 'c12' ),
'integrated_edit_field21' => array( 'location' => 'grid',
'cellId' => 'c13' ),
'integrated_edit_field6' => array( 'location' => 'grid',
'cellId' => 'c14' ),
'integrated_edit_field17' => array( 'location' => 'grid',
'cellId' => 'c16' ),
'integrated_edit_field25' => array( 'location' => 'grid',
'cellId' => 'c17' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'view_header' => array( 'view_header' ),
'view_back_list' => array( 'view_back_list' ),
'view_close' => array( 'view_close' ),
'hamburger' => array( 'hamburger' ),
'view_edit' => array( 'view_edit' ),
'integrated_edit_field' => array( 'integrated_edit_field',
'integrated_edit_field15',
'integrated_edit_field17',
'integrated_edit_field21',
'integrated_edit_field25',
'integrated_edit_field8',
'integrated_edit_field14',
'integrated_edit_field4',
'integrated_edit_field1',
'integrated_edit_field23',
'integrated_edit_field20',
'integrated_edit_field6' ),
'text' => array( 'text' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c8' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c14' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c12' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field20' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c13' => array( 'cols' => array( 1,
2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field21' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field15' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field14' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c16' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field17' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c10' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field23' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c11' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c17' => array( 'cols' => array( 2 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field25' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'text' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 1,
2 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 3,
'height' => 6 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'view',
'breadcrumb' => false,
'nextPrev' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'view',
'type' => 'view',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'view-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 2 ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'view-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'view_back_list',
'view_close' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'hamburger' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'view-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'view_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c8' ),
array( 'cell' => 'c9' ),
array( 'cell' => 'c14' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c12' ),
array( 'cell' => 'c13',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c6' ),
array( 'cell' => 'c7' ),
array( 'cell' => 'c16' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c10' ),
array( 'cell' => 'c11' ),
array( 'cell' => 'c17' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c',
'colspan' => 3 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c5',
'colspan' => 2 ) ) ) ),
'cells' => array( 'c' => array( 'model' => 'c3',
'items' => array( 'text' ),
'useFullWidth' => true ),
'c4' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field8' ) ),
'c5' => array( 'model' => 'c3',
'items' => array(  ) ),
'c6' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field15' ) ),
'c7' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field14' ) ),
'c8' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field' ) ),
'c9' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field4' ) ),
'c11' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field1' ) ),
'c10' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field23' ) ),
'c12' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field20' ) ),
'c13' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field21' ) ),
'c14' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field6' ) ),
'c16' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field17' ) ),
'c17' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field25' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'view_header' => array( 'type' => 'view_header' ),
'view_back_list' => array( 'type' => 'view_back_list' ),
'view_close' => array( 'type' => 'view_close' ),
'hamburger' => array( 'type' => 'hamburger',
'items' => array( 'view_edit' ) ),
'view_edit' => array( 'type' => 'view_edit' ),
'integrated_edit_field' => array( 'field' => 'id',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field15' => array( 'field' => 'evaluado_nombre',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field17' => array( 'field' => 'evaluado_email',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field21' => array( 'field' => 'evaluado_fechaf_po',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field25' => array( 'field' => 'evaluador_email',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'text' => array( 'type' => 'text',
'label' => array( 'text' => '<p>Si desea enviar esta concertación al evaluador seleccione la opción <strong>"<em>En concertación con evauador</em>"</strong> y presione el botón <strong><em>"Enviar concertación"</em></strong></p>',
'type' => 0 ),
'editedByRte' => true ),
'integrated_edit_field8' => array( 'field' => 'estado',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field14' => array( 'field' => 'evaluado_doc',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field4' => array( 'field' => 'vigencia',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field1' => array( 'field' => 'evaluador_doc',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field23' => array( 'field' => 'evaluador_nombre',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field20' => array( 'field' => 'evaluado_fechai_po',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field6' => array( 'field' => 'fchCreacion',
'type' => 'integrated_edit_field',
'orientation' => 0 ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>