<?php
			$optionsArray = array( 'totals' => array( 'id' => array( 'totalsType' => '' ),
'idEvaluado' => array( 'totalsType' => '' ),
'idEvaluador' => array( 'totalsType' => '' ),
'IdEvaluador_c' => array( 'totalsType' => '' ),
'IdEvaluador_d' => array( 'totalsType' => '' ),
'vigencia' => array( 'totalsType' => '' ),
'periodo' => array( 'totalsType' => '' ),
'fchCreacion' => array( 'totalsType' => '' ),
'fchEdefinitiva' => array( 'totalsType' => '' ),
'estado' => array( 'totalsType' => '' ),
'email_not_cierre' => array( 'totalsType' => '' ),
'fecha_not_cierre' => array( 'totalsType' => '' ),
'sys_user' => array( 'totalsType' => '' ),
'evaluado_doc' => array( 'totalsType' => '' ),
'evaluado_nombre' => array( 'totalsType' => '' ),
'evaluado_cargo' => array( 'totalsType' => '' ),
'evaluado_email' => array( 'totalsType' => '' ),
'evaluado_dep_sup' => array( 'totalsType' => '' ),
'evaluado_dep' => array( 'totalsType' => '' ),
'evaluado_fechai_po' => array( 'totalsType' => '' ),
'evaluado_fechaf_po' => array( 'totalsType' => '' ),
'evaluador_doc' => array( 'totalsType' => '' ),
'evaluador_nombre' => array( 'totalsType' => '' ),
'evaluador_cargo' => array( 'totalsType' => '' ),
'evaluador_email' => array( 'totalsType' => '' ),
'evaluador_dep_sup' => array( 'totalsType' => '' ),
'evaluador_dep' => array( 'totalsType' => '' ),
'evaluador_nombramiento' => array( 'totalsType' => '' ),
'evaluado_nombramiento' => array( 'totalsType' => '' ),
'id_comportamental_fk' => array( 'totalsType' => '' ),
'valor_programado' => array( 'totalsType' => '' ),
'valor_comun' => array( 'totalsType' => '' ),
'valor_jerarquico' => array( 'totalsType' => '' ),
'valor_total' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'id',
'vigencia',
'fchCreacion',
'estado',
'evaluador_dep',
'evaluado_doc',
'evaluado_nombre',
'evaluado_cargo',
'evaluado_fechai_po',
'evaluado_fechaf_po',
'evaluador_nombre',
'evaluador_cargo' ),
'exportFields' => array( 'id',
'vigencia',
'fchCreacion',
'estado',
'evaluado_doc',
'evaluado_nombre',
'evaluado_cargo',
'evaluado_fechai_po',
'evaluado_fechaf_po',
'evaluador_nombre',
'evaluador_cargo',
'evaluador_dep' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'id' => array( 'export_field' ),
'vigencia' => array( 'export_field5' ),
'fchCreacion' => array( 'export_field7' ),
'estado' => array( 'export_field9' ),
'evaluador_dep' => array( 'export_field11' ),
'evaluado_doc' => array( 'export_field15' ),
'evaluado_nombre' => array( 'export_field16' ),
'evaluado_cargo' => array( 'export_field17' ),
'evaluado_fechai_po' => array( 'export_field21' ),
'evaluado_fechaf_po' => array( 'export_field22' ),
'evaluador_nombre' => array( 'export_field24' ),
'evaluador_cargo' => array( 'export_field25' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field5',
'export_field7',
'export_field9',
'export_field15',
'export_field16',
'export_field17',
'export_field21',
'export_field22',
'export_field24',
'export_field25',
'export_field11' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field5' => 'grid',
'export_field7' => 'grid',
'export_field9' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field21' => 'grid',
'export_field22' => 'grid',
'export_field24' => 'grid',
'export_field25' => 'grid',
'export_field11' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field5',
'export_field7',
'export_field9',
'export_field11',
'export_field15',
'export_field16',
'export_field17',
'export_field21',
'export_field22',
'export_field24',
'export_field25' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field5',
'export_field7',
'export_field9',
'export_field15',
'export_field16',
'export_field17',
'export_field21',
'export_field22',
'export_field24',
'export_field25',
'export_field11' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'id',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'vigencia',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'fchCreacion',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'estado',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'evaluador_dep',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'evaluado_doc',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'evaluado_nombre',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'evaluado_cargo',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'evaluado_fechai_po',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'evaluado_fechaf_po',
'type' => 'export_field' ),
'export_field24' => array( 'field' => 'evaluador_nombre',
'type' => 'export_field' ),
'export_field25' => array( 'field' => 'evaluador_cargo',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>