<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'id',
'vigencia',
'fchCreacion',
'estado',
'evaluado_doc',
'evaluado_nombre',
'evaluado_cargo',
'evaluado_fechai_po',
'evaluado_fechaf_po',
'evaluador_nombre',
'evaluador_cargo',
'evaluador_dep' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'id' => array( 'import_field' ),
'vigencia' => array( 'import_field5' ),
'fchCreacion' => array( 'import_field7' ),
'estado' => array( 'import_field9' ),
'evaluador_dep' => array( 'import_field11' ),
'evaluado_doc' => array( 'import_field15' ),
'evaluado_nombre' => array( 'import_field16' ),
'evaluado_cargo' => array( 'import_field17' ),
'evaluado_fechai_po' => array( 'import_field21' ),
'evaluado_fechaf_po' => array( 'import_field22' ),
'evaluador_nombre' => array( 'import_field24' ),
'evaluador_cargo' => array( 'import_field25' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field5',
'import_field7',
'import_field9',
'import_field15',
'import_field16',
'import_field17',
'import_field21',
'import_field22',
'import_field24',
'import_field25',
'import_field11' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field5' => 'grid',
'import_field7' => 'grid',
'import_field9' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field17' => 'grid',
'import_field21' => 'grid',
'import_field22' => 'grid',
'import_field24' => 'grid',
'import_field25' => 'grid',
'import_field11' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field5',
'import_field7',
'import_field9',
'import_field11',
'import_field15',
'import_field16',
'import_field17',
'import_field21',
'import_field22',
'import_field24',
'import_field25' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field5',
'import_field7',
'import_field9',
'import_field15',
'import_field16',
'import_field17',
'import_field21',
'import_field22',
'import_field24',
'import_field25',
'import_field11' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'id',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'vigencia',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'fchCreacion',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'estado',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'evaluador_dep',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'evaluado_doc',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'evaluado_nombre',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'evaluado_cargo',
'type' => 'import_field' ),
'import_field21' => array( 'field' => 'evaluado_fechai_po',
'type' => 'import_field' ),
'import_field22' => array( 'field' => 'evaluado_fechaf_po',
'type' => 'import_field' ),
'import_field24' => array( 'field' => 'evaluador_nombre',
'type' => 'import_field' ),
'import_field25' => array( 'field' => 'evaluador_cargo',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>