<?php
			$optionsArray = array( 'totals' => array( 'evaluacion_p_id' => array( 'totalsType' => '' ),
'evaluacion_id_fk' => array( 'totalsType' => '' ),
'idEvaluado' => array( 'totalsType' => '' ),
'idEvaluador' => array( 'totalsType' => '' ),
'IdEvaluador_c' => array( 'totalsType' => '' ),
'IdEvaluador_d' => array( 'totalsType' => '' ),
'vigencia' => array( 'totalsType' => '' ),
'periodo' => array( 'totalsType' => '' ),
'fchCreacion' => array( 'totalsType' => '' ),
'id_eval_vigencia_fk' => array( 'totalsType' => '' ),
'fecha_po_i' => array( 'totalsType' => '' ),
'fecha_po_f' => array( 'totalsType' => '' ),
'estado' => array( 'totalsType' => '' ),
'sys_user' => array( 'totalsType' => '' ),
'evaluado_doc' => array( 'totalsType' => '' ),
'evaluado_nombre' => array( 'totalsType' => '' ),
'evaluado_cargo' => array( 'totalsType' => '' ),
'evaluado_email' => array( 'totalsType' => '' ),
'evaluado_dep_sup' => array( 'totalsType' => '' ),
'evaluado_dep' => array( 'totalsType' => '' ),
'evaluado_nombramiento' => array( 'totalsType' => '' ),
'evaluado_fechai_po' => array( 'totalsType' => '' ),
'evaluado_fechaf_po' => array( 'totalsType' => '' ),
'evaluador_doc' => array( 'totalsType' => '' ),
'evaluador_nombre' => array( 'totalsType' => '' ),
'evaluador_cargo' => array( 'totalsType' => '' ),
'evaluador_email' => array( 'totalsType' => '' ),
'evaluador_dep_sup' => array( 'totalsType' => '' ),
'evaluador_dep' => array( 'totalsType' => '' ),
'sys_date' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array(  ),
'exportFields' => array(  ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array(  ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ),
'grid' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>