<?php
			$optionsArray = array( 'totals' => array( 'evaluacion_p_id' => array( 'totalsType' => '' ),
'evaluacion_id_fk' => array( 'totalsType' => '' ),
'idEvaluado' => array( 'totalsType' => '' ),
'idEvaluador' => array( 'totalsType' => '' ),
'IdEvaluador_c' => array( 'totalsType' => '' ),
'IdEvaluador_d' => array( 'totalsType' => '' ),
'vigencia' => array( 'totalsType' => '' ),
'periodo' => array( 'totalsType' => '' ),
'fchCreacion' => array( 'totalsType' => '' ),
'id_eval_vigencia_fk' => array( 'totalsType' => '' ),
'fecha_po_i' => array( 'totalsType' => '' ),
'fecha_po_f' => array( 'totalsType' => '' ),
'estado' => array( 'totalsType' => '' ),
'sys_user' => array( 'totalsType' => '' ),
'evaluado_doc' => array( 'totalsType' => '' ),
'evaluado_nombre' => array( 'totalsType' => '' ),
'evaluado_cargo' => array( 'totalsType' => '' ),
'evaluado_email' => array( 'totalsType' => '' ),
'evaluado_dep_sup' => array( 'totalsType' => '' ),
'evaluado_dep' => array( 'totalsType' => '' ),
'evaluado_nombramiento' => array( 'totalsType' => '' ),
'evaluado_fechai_po' => array( 'totalsType' => '' ),
'evaluado_fechaf_po' => array( 'totalsType' => '' ),
'evaluador_doc' => array( 'totalsType' => '' ),
'evaluador_nombre' => array( 'totalsType' => '' ),
'evaluador_cargo' => array( 'totalsType' => '' ),
'evaluador_email' => array( 'totalsType' => '' ),
'evaluador_dep_sup' => array( 'totalsType' => '' ),
'evaluador_dep' => array( 'totalsType' => '' ),
'sys_date' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'evaluacion_id_fk',
'idEvaluado',
'idEvaluador',
'IdEvaluador_c',
'IdEvaluador_d',
'vigencia',
'periodo',
'fchCreacion',
'fecha_po_i',
'fecha_po_f',
'estado',
'sys_user',
'evaluado_doc',
'evaluado_nombre',
'evaluado_cargo',
'evaluado_email',
'evaluado_dep_sup',
'evaluado_dep',
'evaluado_nombramiento',
'evaluado_fechai_po',
'evaluado_fechaf_po',
'evaluador_doc',
'evaluador_nombre',
'evaluador_cargo',
'evaluador_email',
'evaluador_dep_sup',
'evaluador_dep',
'id_eval_vigencia_fk' ),
'exportFields' => array( 'evaluacion_id_fk',
'idEvaluado',
'idEvaluador',
'IdEvaluador_c',
'IdEvaluador_d',
'vigencia',
'periodo',
'fchCreacion',
'fecha_po_i',
'fecha_po_f',
'estado',
'sys_user',
'evaluado_doc',
'evaluado_nombre',
'evaluado_cargo',
'evaluado_email',
'evaluado_dep_sup',
'evaluado_dep',
'evaluado_nombramiento',
'evaluado_fechai_po',
'evaluado_fechaf_po',
'evaluador_doc',
'evaluador_nombre',
'evaluador_cargo',
'evaluador_email',
'evaluador_dep_sup',
'evaluador_dep',
'id_eval_vigencia_fk' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'evaluacion_id_fk' => array( 'export_field1' ),
'idEvaluado' => array( 'export_field2' ),
'idEvaluador' => array( 'export_field3' ),
'IdEvaluador_c' => array( 'export_field4' ),
'IdEvaluador_d' => array( 'export_field5' ),
'vigencia' => array( 'export_field6' ),
'periodo' => array( 'export_field7' ),
'fchCreacion' => array( 'export_field8' ),
'fecha_po_i' => array( 'export_field9' ),
'fecha_po_f' => array( 'export_field10' ),
'estado' => array( 'export_field11' ),
'sys_user' => array( 'export_field12' ),
'evaluado_doc' => array( 'export_field13' ),
'evaluado_nombre' => array( 'export_field14' ),
'evaluado_cargo' => array( 'export_field15' ),
'evaluado_email' => array( 'export_field16' ),
'evaluado_dep_sup' => array( 'export_field17' ),
'evaluado_dep' => array( 'export_field18' ),
'evaluado_nombramiento' => array( 'export_field19' ),
'evaluado_fechai_po' => array( 'export_field20' ),
'evaluado_fechaf_po' => array( 'export_field21' ),
'evaluador_doc' => array( 'export_field22' ),
'evaluador_nombre' => array( 'export_field23' ),
'evaluador_cargo' => array( 'export_field24' ),
'evaluador_email' => array( 'export_field25' ),
'evaluador_dep_sup' => array( 'export_field26' ),
'evaluador_dep' => array( 'export_field27' ),
'id_eval_vigencia_fk' => array( 'export_field28' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_field21' => 'grid',
'export_field22' => 'grid',
'export_field23' => 'grid',
'export_field24' => 'grid',
'export_field25' => 'grid',
'export_field26' => 'grid',
'export_field27' => 'grid',
'export_field28' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field1' => array( 'field' => 'evaluacion_id_fk',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'idEvaluado',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'idEvaluador',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'IdEvaluador_c',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'IdEvaluador_d',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'vigencia',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'periodo',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'fchCreacion',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'fecha_po_i',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'fecha_po_f',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'estado',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'sys_user',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'evaluado_doc',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'evaluado_nombre',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'evaluado_cargo',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'evaluado_email',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'evaluado_dep_sup',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'evaluado_dep',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'evaluado_nombramiento',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'evaluado_fechai_po',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'evaluado_fechaf_po',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'evaluador_doc',
'type' => 'export_field' ),
'export_field23' => array( 'field' => 'evaluador_nombre',
'type' => 'export_field' ),
'export_field24' => array( 'field' => 'evaluador_cargo',
'type' => 'export_field' ),
'export_field25' => array( 'field' => 'evaluador_email',
'type' => 'export_field' ),
'export_field26' => array( 'field' => 'evaluador_dep_sup',
'type' => 'export_field' ),
'export_field27' => array( 'field' => 'evaluador_dep',
'type' => 'export_field' ),
'export_field28' => array( 'field' => 'id_eval_vigencia_fk',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>