<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => false ),
'details' => array( 'evaluacion_p_comportamental_th' => array( 'displayPreview' => 1 ),
'evaluacion_p_funcional_th' => array( 'displayPreview' => 1 ),
'evidencias_p_th' => array( 'displayPreview' => 1 ) ),
'master' => array( 'concertacion_th' => array( 'preview' => false ) ),
'totals' => array( 'evaluacion_p_id' => array( 'totalsType' => '' ),
'evaluacion_id_fk' => array( 'totalsType' => '' ),
'idEvaluado' => array( 'totalsType' => '' ),
'idEvaluador' => array( 'totalsType' => '' ),
'IdEvaluador_c' => array( 'totalsType' => '' ),
'IdEvaluador_d' => array( 'totalsType' => '' ),
'vigencia' => array( 'totalsType' => '' ),
'periodo' => array( 'totalsType' => '' ),
'fchCreacion' => array( 'totalsType' => '' ),
'id_eval_vigencia_fk' => array( 'totalsType' => '' ),
'fecha_po_i' => array( 'totalsType' => '' ),
'fecha_po_f' => array( 'totalsType' => '' ),
'estado' => array( 'totalsType' => '' ),
'sys_user' => array( 'totalsType' => '' ),
'evaluado_doc' => array( 'totalsType' => '' ),
'evaluado_nombre' => array( 'totalsType' => '' ),
'evaluado_cargo' => array( 'totalsType' => '' ),
'evaluado_email' => array( 'totalsType' => '' ),
'evaluado_dep_sup' => array( 'totalsType' => '' ),
'evaluado_dep' => array( 'totalsType' => '' ),
'evaluado_nombramiento' => array( 'totalsType' => '' ),
'evaluado_fechai_po' => array( 'totalsType' => '' ),
'evaluado_fechaf_po' => array( 'totalsType' => '' ),
'evaluador_doc' => array( 'totalsType' => '' ),
'evaluador_nombre' => array( 'totalsType' => '' ),
'evaluador_cargo' => array( 'totalsType' => '' ),
'evaluador_email' => array( 'totalsType' => '' ),
'evaluador_dep_sup' => array( 'totalsType' => '' ),
'evaluador_dep' => array( 'totalsType' => '' ),
'sys_date' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array(  ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array(  ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'print_pages',
'grid_inline_cancel',
'inline_add' ),
'below-grid' => array(  ),
'top' => array( 'print_header',
'print_subheader' ),
'grid' => array( 'details_preview',
'details_preview1',
'details_preview2' ) ),
'formXtTags' => array( 'above-grid' => array( 'print_pages',
'inline_cancel',
'inlineadd_link' ),
'below-grid' => array(  ) ),
'itemForms' => array( 'print_pages' => 'above-grid',
'grid_inline_cancel' => 'above-grid',
'inline_add' => 'above-grid',
'print_header' => 'top',
'print_subheader' => 'top',
'details_preview' => 'grid',
'details_preview1' => 'grid',
'details_preview2' => 'grid' ),
'itemLocations' => array( 'details_preview' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview' ),
'details_preview1' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview' ),
'details_preview2' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'print_header' => array( 'print_header' ),
'print_subheader' => array( 'print_subheader' ),
'print_pages' => array( 'print_pages' ),
'details_preview' => array( 'details_preview',
'details_preview1',
'details_preview2' ),
'inline_add' => array( 'inline_add' ),
'grid_inline_cancel' => array( 'grid_inline_cancel' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'cell_dpreview' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'details_preview',
'details_preview1',
'details_preview2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 0,
'height' => 4 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array( 'print_pages' => array( 'tag' => 'PRINT_PAGES',
'type' => 2 ) ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'gridType' => 0,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'print',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'print',
'type' => 'print',
'layoutId' => 'basic',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'print-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'print_pages',
'grid_inline_cancel',
'inline_add' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'print-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'print-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'print_header',
'print_subheader' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array(  ) ),
array( 'section' => 'body',
'cells' => array(  ) ),
array( 'cells' => array( array( 'cell' => 'cell_dpreview' ) ),
'section' => 'body' ),
array( 'section' => 'foot',
'cells' => array(  ) ) ),
'cells' => array( 'cell_dpreview' => array( 'model' => 'cell_dpreview',
'items' => array( 'details_preview',
'details_preview1',
'details_preview2' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'print_header' => array( 'type' => 'print_header' ),
'print_subheader' => array( 'type' => 'print_subheader' ),
'print_pages' => array( 'type' => 'print_pages' ),
'details_preview' => array( 'type' => 'details_preview',
'table' => 'evaluacion_p_comportamental_th',
'items' => array(  ),
'popup' => false ),
'details_preview1' => array( 'type' => 'details_preview',
'table' => 'evidencias_p_th',
'items' => array(  ),
'popup' => false ),
'details_preview2' => array( 'type' => 'details_preview',
'table' => 'evaluacion_p_funcional_th',
'items' => array(  ),
'popup' => false ),
'inline_add' => array( 'type' => 'inline_add',
'detailsOnly' => true ),
'grid_inline_cancel' => array( 'type' => 'grid_inline_cancel' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>