<?php
			$optionsArray = array( 'details' => array( 'evaluacion_p_comportamental' => array( 'displayPreview' => 2,
'previewPageId' => '' ),
'evaluacion_p_funcional' => array( 'displayPreview' => 2,
'previewPageId' => '' ),
'evidencias_p' => array( 'displayPreview' => 2,
'previewPageId' => '' ) ),
'master' => array( 'concertacion_po_3se' => array( 'preview' => false ),
'concertacion_po_3s' => array( 'preview' => false ) ),
'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 'evaluacion_id_fk',
'idEvaluado',
'idEvaluador',
'IdEvaluador_c',
'IdEvaluador_d',
'vigencia',
'periodo',
'fchCreacion',
'fecha_po_i',
'fecha_po_f',
'estado',
'sys_user',
'evaluado_doc',
'evaluado_nombre',
'evaluado_cargo',
'evaluado_email',
'evaluado_dep_sup',
'evaluado_dep',
'evaluado_nombramiento',
'evaluado_fechai_po',
'evaluado_fechaf_po',
'evaluador_doc',
'evaluador_nombre',
'evaluador_cargo',
'evaluador_email',
'evaluador_dep_sup',
'evaluador_dep',
'id_eval_vigencia_fk' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'updateOnEditFields' => array(  ),
'fieldItems' => array( 'evaluacion_id_fk' => array( 'integrated_edit_field' ),
'idEvaluado' => array( 'integrated_edit_field1' ),
'idEvaluador' => array( 'integrated_edit_field2' ),
'IdEvaluador_c' => array( 'integrated_edit_field3' ),
'IdEvaluador_d' => array( 'integrated_edit_field4' ),
'vigencia' => array( 'integrated_edit_field5' ),
'periodo' => array( 'integrated_edit_field6' ),
'fchCreacion' => array( 'integrated_edit_field7' ),
'fecha_po_i' => array( 'integrated_edit_field8' ),
'fecha_po_f' => array( 'integrated_edit_field9' ),
'estado' => array( 'integrated_edit_field10' ),
'sys_user' => array( 'integrated_edit_field11' ),
'evaluado_doc' => array( 'integrated_edit_field12' ),
'evaluado_nombre' => array( 'integrated_edit_field13' ),
'evaluado_cargo' => array( 'integrated_edit_field14' ),
'evaluado_email' => array( 'integrated_edit_field15' ),
'evaluado_dep_sup' => array( 'integrated_edit_field16' ),
'evaluado_dep' => array( 'integrated_edit_field17' ),
'evaluado_nombramiento' => array( 'integrated_edit_field18' ),
'evaluado_fechai_po' => array( 'integrated_edit_field19' ),
'evaluado_fechaf_po' => array( 'integrated_edit_field20' ),
'evaluador_doc' => array( 'integrated_edit_field21' ),
'evaluador_nombre' => array( 'integrated_edit_field22' ),
'evaluador_cargo' => array( 'integrated_edit_field23' ),
'evaluador_email' => array( 'integrated_edit_field24' ),
'evaluador_dep_sup' => array( 'integrated_edit_field25' ),
'evaluador_dep' => array( 'integrated_edit_field26' ),
'id_eval_vigencia_fk' => array( 'integrated_edit_field27' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => true,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'edit_message' ),
'below-grid' => array( 'edit_save',
'edit_back_list',
'edit_close',
'hamburger' ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'loginform_login',
'username_button' ),
'left' => array( 'logo',
'expand_button',
'menu' ),
'top' => array( 'edit_header' ),
'grid' => array( 'tabs' ),
'section' => array( 'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field',
'integrated_edit_field11',
'integrated_edit_field10',
'integrated_edit_field27' ),
'section1' => array( 'integrated_edit_field7',
'integrated_edit_field2',
'integrated_edit_field1',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field17',
'integrated_edit_field18',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field22',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field25',
'integrated_edit_field26' ) ),
'formXtTags' => array( 'above-grid' => array( 'message_block' ) ),
'itemForms' => array( 'edit_message' => 'above-grid',
'edit_save' => 'below-grid',
'edit_back_list' => 'below-grid',
'edit_close' => 'below-grid',
'hamburger' => 'below-grid',
'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'logo' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'edit_header' => 'top',
'tabs' => 'grid',
'integrated_edit_field8' => 'section',
'integrated_edit_field9' => 'section',
'integrated_edit_field' => 'section',
'integrated_edit_field11' => 'section',
'integrated_edit_field10' => 'section',
'integrated_edit_field27' => 'section',
'integrated_edit_field7' => 'section1',
'integrated_edit_field2' => 'section1',
'integrated_edit_field1' => 'section1',
'integrated_edit_field3' => 'section1',
'integrated_edit_field4' => 'section1',
'integrated_edit_field5' => 'section1',
'integrated_edit_field6' => 'section1',
'integrated_edit_field12' => 'section1',
'integrated_edit_field13' => 'section1',
'integrated_edit_field14' => 'section1',
'integrated_edit_field15' => 'section1',
'integrated_edit_field16' => 'section1',
'integrated_edit_field17' => 'section1',
'integrated_edit_field18' => 'section1',
'integrated_edit_field19' => 'section1',
'integrated_edit_field20' => 'section1',
'integrated_edit_field21' => 'section1',
'integrated_edit_field22' => 'section1',
'integrated_edit_field23' => 'section1',
'integrated_edit_field24' => 'section1',
'integrated_edit_field25' => 'section1',
'integrated_edit_field26' => 'section1' ),
'itemLocations' => array( 'tabs' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field8' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field9' => array( 'location' => 'section',
'cellId' => 'c' ),
'integrated_edit_field' => array( 'location' => 'section',
'cellId' => 'c2' ),
'integrated_edit_field11' => array( 'location' => 'section',
'cellId' => 'c3' ),
'integrated_edit_field10' => array( 'location' => 'section',
'cellId' => 'c4' ),
'integrated_edit_field27' => array( 'location' => 'section',
'cellId' => 'c8' ),
'integrated_edit_field7' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field2' => array( 'location' => 'section1',
'cellId' => 'c3' ),
'integrated_edit_field1' => array( 'location' => 'section1',
'cellId' => 'c4' ),
'integrated_edit_field3' => array( 'location' => 'section1',
'cellId' => 'c5' ),
'integrated_edit_field4' => array( 'location' => 'section1',
'cellId' => 'c6' ),
'integrated_edit_field5' => array( 'location' => 'section1',
'cellId' => 'c7' ),
'integrated_edit_field6' => array( 'location' => 'section1',
'cellId' => 'c8' ),
'integrated_edit_field12' => array( 'location' => 'section1',
'cellId' => 'c9' ),
'integrated_edit_field13' => array( 'location' => 'section1',
'cellId' => 'c10' ),
'integrated_edit_field14' => array( 'location' => 'section1',
'cellId' => 'c11' ),
'integrated_edit_field15' => array( 'location' => 'section1',
'cellId' => 'c12' ),
'integrated_edit_field16' => array( 'location' => 'section1',
'cellId' => 'c13' ),
'integrated_edit_field17' => array( 'location' => 'section1',
'cellId' => 'c14' ),
'integrated_edit_field18' => array( 'location' => 'section1',
'cellId' => 'c15' ),
'integrated_edit_field19' => array( 'location' => 'section1',
'cellId' => 'c16' ),
'integrated_edit_field20' => array( 'location' => 'section1',
'cellId' => 'c17' ),
'integrated_edit_field21' => array( 'location' => 'section1',
'cellId' => 'c18' ),
'integrated_edit_field22' => array( 'location' => 'section1',
'cellId' => 'c19' ),
'integrated_edit_field23' => array( 'location' => 'section1',
'cellId' => 'c20' ),
'integrated_edit_field24' => array( 'location' => 'section1',
'cellId' => 'c21' ),
'integrated_edit_field25' => array( 'location' => 'section1',
'cellId' => 'c22' ),
'integrated_edit_field26' => array( 'location' => 'section1',
'cellId' => 'c23' ) ),
'itemVisiblity' => array( 'expand_menu_button' => 2,
'expand_button' => 5 ) ),
'itemsByType' => array( 'edit_header' => array( 'edit_header' ),
'hamburger' => array( 'hamburger' ),
'edit_reset' => array( 'edit_reset' ),
'edit_message' => array( 'edit_message' ),
'edit_save' => array( 'edit_save' ),
'edit_back_list' => array( 'edit_back_list' ),
'edit_close' => array( 'edit_close' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'changepassword_link' => array( 'changepassword_link' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'edit_view' => array( 'edit_view' ),
'integrated_edit_field' => array( 'integrated_edit_field',
'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field17',
'integrated_edit_field18',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field22',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field27' ),
'tabs' => array( 'tabs' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'tabs' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section' => array( 'cells' => array( 'c2' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field11' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field27' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c1' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field10' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 4 ),
'section1' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field12' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c10' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field13' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c11' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field14' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c12' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field15' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c13' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field16' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c14' => array( 'cols' => array( 2 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field17' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c15' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field18' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c16' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field19' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c17' => array( 'cols' => array( 2 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field20' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c18' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field21' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c19' => array( 'cols' => array( 1 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field22' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c20' => array( 'cols' => array( 2 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field23' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c21' => array( 'cols' => array( 0 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field24' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c22' => array( 'cols' => array( 1 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field25' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c23' => array( 'cols' => array( 2 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field26' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c1' => array( 'cols' => array( 0 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 1 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 2 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 3,
'height' => 8 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array( array( 'id' => 'main',
'horizontal' => false ) ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'edit',
'breadcrumb' => false,
'nextPrev' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'edit' => array( 'updateSelected' => false ) );
			$pageArray = array( 'id' => 'edit',
'type' => 'edit',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'edit-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_message' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'edit-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_save',
'edit_back_list',
'edit_close' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'hamburger' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo',
'expand_button' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'edit-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'tabs' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c8' ),
array( 'cell' => 'c9' ) ) ),
array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c5' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field8' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field9' ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field' ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field11' ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field10' ) ),
'c5' => array( 'model' => 'c1',
'items' => array(  ) ),
'c8' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field27' ) ),
'c9' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section1' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c3' ),
array( 'cell' => 'c4' ),
array( 'cell' => 'c5' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c6' ),
array( 'cell' => 'c7' ),
array( 'cell' => 'c8' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c9' ),
array( 'cell' => 'c10' ),
array( 'cell' => 'c11' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c12' ),
array( 'cell' => 'c13' ),
array( 'cell' => 'c14' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c15' ),
array( 'cell' => 'c16' ),
array( 'cell' => 'c17' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c18' ),
array( 'cell' => 'c19' ),
array( 'cell' => 'c20' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c21' ),
array( 'cell' => 'c22' ),
array( 'cell' => 'c23' ) ) ),
array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field7' ) ),
'c' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c1',
'items' => array(  ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field2' ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field1' ) ),
'c5' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field3' ) ),
'c6' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field4' ) ),
'c7' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field5' ) ),
'c8' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field6' ) ),
'c9' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field12' ) ),
'c10' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field13' ) ),
'c11' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field14' ) ),
'c12' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field15' ) ),
'c13' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field16' ) ),
'c14' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field17' ) ),
'c15' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field18' ) ),
'c16' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field19' ) ),
'c17' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field20' ) ),
'c18' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field21' ) ),
'c19' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field22' ) ),
'c20' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field23' ) ),
'c21' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field24' ) ),
'c22' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field25' ) ),
'c23' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field26' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'edit_header' => array( 'type' => 'edit_header' ),
'hamburger' => array( 'type' => 'hamburger',
'items' => array( 'edit_reset',
'edit_view' ) ),
'edit_reset' => array( 'type' => 'edit_reset' ),
'edit_message' => array( 'type' => 'edit_message' ),
'edit_save' => array( 'type' => 'edit_save' ),
'edit_back_list' => array( 'type' => 'edit_back_list' ),
'edit_close' => array( 'type' => 'edit_close' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link',
'changepassword_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'edit_view' => array( 'type' => 'edit_view' ),
'integrated_edit_field' => array( 'field' => 'evaluacion_id_fk',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'evaluacion_id_fk',
'table' => 'evaluacion_po',
'type' => 3 ) ),
'integrated_edit_field1' => array( 'field' => 'idEvaluado',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field2' => array( 'field' => 'idEvaluador',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field3' => array( 'field' => 'IdEvaluador_c',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field4' => array( 'field' => 'IdEvaluador_d',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field5' => array( 'field' => 'vigencia',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field6' => array( 'field' => 'periodo',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field7' => array( 'field' => 'fchCreacion',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field8' => array( 'field' => 'fecha_po_i',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field9' => array( 'field' => 'fecha_po_f',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field10' => array( 'field' => 'estado',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field11' => array( 'field' => 'sys_user',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'sys_user',
'table' => 'evaluacion_po',
'type' => 3 ) ),
'integrated_edit_field12' => array( 'field' => 'evaluado_doc',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field13' => array( 'field' => 'evaluado_nombre',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field14' => array( 'field' => 'evaluado_cargo',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field15' => array( 'field' => 'evaluado_email',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field16' => array( 'field' => 'evaluado_dep_sup',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field17' => array( 'field' => 'evaluado_dep',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field18' => array( 'field' => 'evaluado_nombramiento',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field19' => array( 'field' => 'evaluado_fechai_po',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field20' => array( 'field' => 'evaluado_fechaf_po',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field21' => array( 'field' => 'evaluador_doc',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field22' => array( 'field' => 'evaluador_nombre',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field23' => array( 'field' => 'evaluador_cargo',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field24' => array( 'field' => 'evaluador_email',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field25' => array( 'field' => 'evaluador_dep_sup',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field26' => array( 'field' => 'evaluador_dep',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field27' => array( 'field' => 'id_eval_vigencia_fk',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'tabs' => array( 'type' => 'tabs',
'titles' => array( array( 'text' => 'Nueva evaluación',
'type' => 0 ),
array( 'text' => '',
'type' => 0 ) ),
'locations' => array( 'section',
'section1' ),
'bsStyle' => 'default',
'panelType' => 2 ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>