<?php
			$optionsArray = array( 'list' => array( 'inlineAdd' => true,
'detailsAdd' => true,
'inlineEdit' => true,
'spreadsheetMode' => false,
'reorderRows' => false,
'addToBottom' => false,
'delete' => false,
'updateSelected' => false,
'addInPopup' => null,
'editInPopup' => null,
'viewInPopup' => null,
'clickSort' => true,
'sortDropdown' => false,
'showHideFields' => false,
'reorderFields' => false,
'fieldFilter' => false,
'hideNumberOfRecords' => false ),
'master' => array( 'q_caldef_p_x005' => array( 'preview' => true ),
'q_caldef_p_x005_adm' => array( 'preview' => true ),
'q_caldef_p_x005_evaluador' => array( 'preview' => true ) ),
'listSearch' => array( 'alwaysOnPanelFields' => array(  ),
'searchPanel' => false,
'fixedSearchPanel' => false,
'simpleSearchOptions' => false,
'searchSaving' => false ),
'totals' => array( 'id' => array( 'totalsType' => '' ),
'idEvaluado' => array( 'totalsType' => '' ),
'idEvaluador' => array( 'totalsType' => '' ),
'idEvaluadorFinal' => array( 'totalsType' => '' ),
'IdEvaluador_c' => array( 'totalsType' => '' ),
'IdEvaluador_d' => array( 'totalsType' => '' ),
'vigencia' => array( 'totalsType' => '' ),
'periodo' => array( 'totalsType' => '' ),
'fchCreacion' => array( 'totalsType' => '' ),
'fchEdefinitiva' => array( 'totalsType' => '' ),
'estado' => array( 'totalsType' => '' ),
'email_not_cierre' => array( 'totalsType' => '' ),
'fecha_not_cierre' => array( 'totalsType' => '' ),
'sys_user' => array( 'totalsType' => '' ),
'evaluado_doc' => array( 'totalsType' => '' ),
'evaluado_nombre' => array( 'totalsType' => '' ),
'evaluado_cargo' => array( 'totalsType' => '' ),
'evaluado_email' => array( 'totalsType' => '' ),
'evaluado_dep_sup' => array( 'totalsType' => '' ),
'evaluado_dep' => array( 'totalsType' => '' ),
'evaluado_nombramiento' => array( 'totalsType' => '' ),
'evaluado_fechai_po' => array( 'totalsType' => '' ),
'evaluado_fechaf_po' => array( 'totalsType' => '' ),
'evaluado_fechai_pp' => array( 'totalsType' => '' ),
'evaluado_fechaf_pp' => array( 'totalsType' => '' ),
'evaluador_doc' => array( 'totalsType' => '' ),
'evaluador_nombre' => array( 'totalsType' => '' ),
'evaluador_cargo' => array( 'totalsType' => '' ),
'evaluador_email' => array( 'totalsType' => '' ),
'evaluador_dep_sup' => array( 'totalsType' => '' ),
'evaluador_dep' => array( 'totalsType' => '' ),
'sys_date' => array( 'totalsType' => '' ),
'evaluador_nombramiento' => array( 'totalsType' => '' ),
'valor_funcional' => array( 'totalsType' => '' ),
'valor_programado' => array( 'totalsType' => '' ),
'valor_pendiente' => array( 'totalsType' => '' ),
'id_comportamental_fk' => array( 'totalsType' => '' ),
'valor_comun' => array( 'totalsType' => '' ),
'valor_jerarquico' => array( 'totalsType' => '' ),
'valor_total' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'idEvaluador',
'idEvaluadorFinal' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'filterFields' => array(  ),
'inlineAddFields' => array(  ),
'inlineEditFields' => array( 'idEvaluador',
'idEvaluadorFinal' ),
'fieldItems' => array( 'idEvaluador' => array( 'simple_grid_field',
'simple_grid_field2' ),
'idEvaluadorFinal' => array( 'simple_grid_field40',
'simple_grid_field39' ) ),
'hideEmptyFields' => array(  ),
'fieldFilterFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'inline_add',
'inline_save_all',
'inline_cancel_all',
'custom_button',
'details_found',
'page_size',
'print_panel' ),
'below-grid' => array( 'pagination' ),
'left' => array( 'logo',
'expand_button',
'menu' ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb',
'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'grid' => array( 'simple_grid_field',
'simple_grid_field2',
'simple_grid_field40',
'simple_grid_field39',
'grid_inline_edit',
'grid_inline_save',
'grid_inline_cancel',
'grid_checkbox_head',
'grid_checkbox' ),
'top' => array( 'master_info' ) ),
'formXtTags' => array( 'below-grid' => array( 'pagination' ),
'top' => array( 'mastertable_block' ) ),
'itemForms' => array( 'inline_add' => 'above-grid',
'inline_save_all' => 'above-grid',
'inline_cancel_all' => 'above-grid',
'custom_button' => 'above-grid',
'details_found' => 'above-grid',
'page_size' => 'above-grid',
'print_panel' => 'above-grid',
'pagination' => 'below-grid',
'logo' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'breadcrumb' => 'supertop',
'simple_search' => 'supertop',
'list_options' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'simple_grid_field' => 'grid',
'simple_grid_field2' => 'grid',
'simple_grid_field40' => 'grid',
'simple_grid_field39' => 'grid',
'grid_inline_edit' => 'grid',
'grid_inline_save' => 'grid',
'grid_inline_cancel' => 'grid',
'grid_checkbox_head' => 'grid',
'grid_checkbox' => 'grid',
'master_info' => 'top' ),
'itemLocations' => array( 'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field40' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'simple_grid_field39' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'grid_inline_edit' => array( 'location' => 'grid',
'cellId' => 'cell_icons' ),
'grid_inline_save' => array( 'location' => 'grid',
'cellId' => 'cell_icons' ),
'grid_inline_cancel' => array( 'location' => 'grid',
'cellId' => 'cell_icons' ),
'grid_checkbox_head' => array( 'location' => 'grid',
'cellId' => 'headcell_checkbox' ),
'grid_checkbox' => array( 'location' => 'grid',
'cellId' => 'cell_checkbox' ) ),
'itemVisiblity' => array( 'breadcrumb' => 5,
'expand_menu_button' => 2,
'print_panel' => 5,
'expand_button' => 5 ) ),
'itemsByType' => array( 'page_size' => array( 'page_size' ),
'details_found' => array( 'details_found' ),
'breadcrumb' => array( 'breadcrumb' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'pagination' => array( 'pagination' ),
'grid_field_label' => array( 'simple_grid_field',
'simple_grid_field40' ),
'list_options' => array( 'list_options' ),
'grid_field' => array( 'simple_grid_field2',
'simple_grid_field39' ),
'-' => array( '-3',
'-6',
'-',
'-4',
'-1',
'-2',
'-5' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'changepassword_link' => array( 'changepassword_link' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'advsearch_link' => array( 'advsearch_link' ),
'export_selected' => array( 'export_selected' ),
'grid_checkbox' => array( 'grid_checkbox' ),
'grid_inline_edit' => array( 'grid_inline_edit' ),
'inline_cancel_all' => array( 'inline_cancel_all' ),
'grid_checkbox_head' => array( 'grid_checkbox_head' ),
'inline_save_all' => array( 'inline_save_all' ),
'grid_inline_save' => array( 'grid_inline_save' ),
'grid_inline_cancel' => array( 'grid_inline_cancel' ),
'print_panel' => array( 'print_panel' ),
'adminarea_link' => array( 'adminarea_link' ),
'edit_selected' => array( 'edit_selected' ),
'inline_add' => array( 'inline_add' ),
'master_info' => array( 'master_info' ),
'export' => array( 'export' ),
'custom_button' => array( 'custom_button' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox_head' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array( 'idEvaluador_fieldheadercolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field1' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'idEvaluadorFinal_fieldheadercolumn' ),
'items' => array( 'simple_grid_field40' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'inlineedit_column',
'inline_save',
'inline_cancel' ),
'items' => array( 'grid_inline_edit',
'grid_inline_save',
'grid_inline_cancel' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'idEvaluador_fieldcolumn' ),
'items' => array( 'simple_grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'idEvaluadorFinal_fieldcolumn' ),
'items' => array( 'simple_grid_field39' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 4,
'height' => 3 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array( 'details_found' => array( 'tag' => 'DISPLAYING',
'type' => 2 ) ) ),
'gridType' => 0,
'recsPerRow' => 1,
'hasCustomButtons' => true,
'customButtons' => array( 'Help001' ),
'hasNotifications' => false,
'menus' => array( array( 'id' => 'main',
'horizontal' => false ) ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'list',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array( 'Help001' ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'list',
'type' => 'list',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'list-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'inline_add',
'inline_save_all',
'inline_cancel_all',
'custom_button' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'details_found',
'page_size',
'print_panel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'list-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'pagination' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo',
'expand_button' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'list_options',
'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_icons' ),
array( 'cell' => 'headcell_checkbox' ),
array( 'cell' => 'headcell_field' ),
array( 'cell' => 'headcell_field1' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_icons' ),
array( 'cell' => 'cell_checkbox' ),
array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field1' ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_icons' ),
array( 'cell' => 'footcell_checkbox' ),
array( 'cell' => 'footcell_field' ),
array( 'cell' => 'footcell_field1' ) ) ) ),
'cells' => array( 'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field' ),
'field' => 'idEvaluador',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field2' ),
'field' => 'idEvaluador',
'columnName' => 'field' ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field40' ),
'field' => 'idEvaluadorFinal',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field39' ),
'field' => 'idEvaluadorFinal',
'columnName' => 'field' ),
'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_icons' => array( 'model' => 'headcell_icons',
'items' => array(  ) ),
'cell_icons' => array( 'model' => 'cell_icons',
'items' => array( 'grid_inline_edit',
'grid_inline_save',
'grid_inline_cancel' ) ),
'footcell_icons' => array( 'model' => 'footcell_icons',
'items' => array(  ) ),
'headcell_checkbox' => array( 'model' => 'headcell_checkbox',
'items' => array( 'grid_checkbox_head' ) ),
'cell_checkbox' => array( 'model' => 'cell_checkbox',
'items' => array( 'grid_checkbox' ) ),
'footcell_checkbox' => array( 'model' => 'footcell_checkbox',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'list-sidebar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'master_info' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'page_size' => array( 'type' => 'page_size' ),
'details_found' => array( 'type' => 'details_found' ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'simple_search' => array( 'type' => 'simple_search' ),
'pagination' => array( 'type' => 'pagination' ),
'simple_grid_field' => array( 'type' => 'grid_field_label',
'field' => 'idEvaluador',
'clickSort' => true ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'edit_selected',
'export_selected',
'-5',
'advsearch_link',
'-6',
'export' ) ),
'simple_grid_field40' => array( 'type' => 'grid_field_label',
'field' => 'idEvaluadorFinal',
'clickSort' => true ),
'simple_grid_field2' => array( 'field' => 'idEvaluador',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => true,
'clickSort' => true ),
'-3' => array( 'type' => '-' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link',
'changepassword_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'-6' => array( 'type' => '-' ),
'-' => array( 'type' => '-' ),
'-4' => array( 'type' => '-' ),
'-1' => array( 'type' => '-' ),
'advsearch_link' => array( 'type' => 'advsearch_link' ),
'-2' => array( 'type' => '-' ),
'export_selected' => array( 'type' => 'export_selected' ),
'grid_checkbox' => array( 'type' => 'grid_checkbox' ),
'grid_inline_edit' => array( 'type' => 'grid_inline_edit' ),
'inline_cancel_all' => array( 'type' => 'inline_cancel_all' ),
'grid_checkbox_head' => array( 'type' => 'grid_checkbox_head' ),
'inline_save_all' => array( 'type' => 'inline_save_all' ),
'grid_inline_save' => array( 'type' => 'grid_inline_save' ),
'grid_inline_cancel' => array( 'type' => 'grid_inline_cancel' ),
'print_panel' => array( 'type' => 'print_panel',
'items' => array(  ) ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'-5' => array( 'type' => '-' ),
'edit_selected' => array( 'type' => 'edit_selected' ),
'simple_grid_field39' => array( 'field' => 'idEvaluadorFinal',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => true,
'clickSort' => true ),
'inline_add' => array( 'type' => 'inline_add' ),
'master_info' => array( 'type' => 'master_info',
'tables' => array( 'q_caldef_p_x005' => 'true',
'q_caldef_p_x005_adm' => 'true',
'q_caldef_p_x005_evaluador' => 'true' ) ),
'export' => array( 'type' => 'export' ),
'custom_button' => array( 'type' => 'custom_button',
'eventId' => 'Help001',
'label' => array( 'text' => 'Ayuda ',
'type' => 0 ),
'icon' => array( 'fa' => 'question-circle' ),
'buttonStyle' => 'warning' ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'spreadsheetGrid' => false,
'version' => 14,
'reorderRows' => false,
'reorderRowsField' => '',
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>