<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_concertacion_po_2  extends eventsBase
{
	function __construct()
	{
	// fill list of events


		$this->events["BeforeMoveNextList"]=true;

		$this->events["AfterEdit"]=true;



	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: After record processed
function BeforeMoveNextList(&$data, &$row, &$record, $recordId, $pageObject)
{

		// Atualiza el valor en acuerdos funcionales
$sql = "UPDATE
	edl_sp.evaluacion
	INNER JOIN
	edl_sp.q_edl2_ctrl_valor_af_002
	ON 
		edl_sp.evaluacion.id = edl_sp.q_edl2_ctrl_valor_af_002.radicado
			SET
	edl_sp.evaluacion.valor_programado =	edl_sp.q_edl2_ctrl_valor_af_002.valor_proyectado;";
CustomQuery($sql);

// Atualiza el valor en acuerdos comportamental comun

$sql = "UPDATE
	edl_sp.evaluacion
	INNER JOIN
	edl_sp.q_edl2_ctrl_valor_ac_000
	ON 
		edl_sp.evaluacion.id = edl_sp.q_edl2_ctrl_valor_ac_000.idEvaluacion_FK
		SET
	edl_sp.evaluacion.valor_comun =	edl_sp.q_edl2_ctrl_valor_ac_000.qty_comun;";
CustomQuery($sql);

// Atualiza el valor en acuerdos comportamental jerarquico

$sql = "UPDATE edl_sp.evaluacion
INNER JOIN edl_sp.q_edl2_ctrl_valor_aj_000 ON edl_sp.evaluacion.id = edl_sp.q_edl2_ctrl_valor_aj_000.idEvaluacion_FK 
SET edl_sp.evaluacion.valor_jerarquico = edl_sp.q_edl2_ctrl_valor_aj_000.qty_jerarquica;";
CustomQuery($sql);

// Atualiza el valor total de concertación

$sql = "UPDATE
	edl_sp.evaluacion
	SET
	edl_sp.evaluacion.valor_total = (edl_sp.evaluacion.valor_programado + edl_sp.evaluacion.valor_comun + edl_sp.evaluacion.valor_jerarquico);";
CustomQuery($sql);



// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function BeforeMoveNextList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record updated
function AfterEdit(&$values, $where, &$oldvalues, &$keys, $inline, $pageObject)
{

		//**********  Send email with new data  ************

$email=$values['evaluador_email'];
$from="EDL_2021@mincit.gov.co";
$fromName="Evaluación del Desempeño Laboral | MinCIT";
$msg="<p>Hola, <strong>".$values['evaluado_nombre']."</strong> ha finalizado la etapa de  concertación de acuerdos funcionales y competencias comportamentales con el  número de radicado <strong>".$values['id']."</strong> - <strong>".$values['vigencia']."</strong>, es el momento de fijar la fecha de concertación definitiva con el evaluado.<br />
  Información del radicado:</p>
<table border='0' cellspacing='3' cellpadding='0'>
  <tr>
    <td><br />
        <strong>RADICADO    / PERIODO</strong> </td>
    <td><p><strong>".$values['id']."</strong></p></td>
  </tr>
  <tr>
    <td><p><strong>EVALUADO</strong></p></td>
    <td><p><strong>".$values['evaluado_nombre']."</strong></p></td>
  </tr>
  <tr>
    <td><p><strong>DOCUMENTO</strong></p></td>
    <td><p><strong>".$values['evaluado_doc']."</strong></p></td>
  </tr>
  <tr>
    <td><p><strong>CORREO ELECTRÓNICO</strong></p></td>
    <td><p><strong>".$values['evaluado_email']."</strong></p></td>
  </tr>
  <tr>
    <td><p><strong>EVALUADOR</strong></p></td>
    <td><p><strong>".$values['evaluador_nombre']."</strong></p></td>
  </tr>
  <tr>
    <td><p><strong>FECHA INICIO</strong></p></td>
    <td><p><strong>".$values['evaluado_fechai_po']."</strong></p></td>
  </tr>
  <tr>
    <td><p><strong>FECHA FINAL   </strong></p></td>
    <td><p><strong>".$values['evaluado_fechaf_po']."</strong></p></td>
  </tr>
</table>
<p><a href='http://servicios.mincit.gov.co/edl2' target='_blank'>Ingresar al  sitio Web EDL</a><br />
  Cordialmente,<br />
  <strong>Área Funcional de Talento Humano</strong><br />
  Secretaría General<br />
  Ministerio de Comercio, Industria y Turismo</p>";
$subject=".:: EDL :: Radicado::".$values['id'];

//$msg.= "Name: ".$values["name"]."\r\n";
//$msg.= "Email: ".$values["email"]."\r\n";
//$msg.= "Age: ".$values["age"]."\r\n";

$ret=runner_mail(array('to' => $email, 'bcc' => 'dito73@gmail.com', 'subject' => $subject, 'htmlbody' => $msg, 'from'=>$from));
if(!$ret["mailed"])
	echo $ret["message"];


// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
