<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_evaluacion_po  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["AfterAdd"]=true;

		$this->events["BeforeMoveNextList"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, $pageObject)
{

		
// ACUTALIZACION DE COMPROMISOS COMPORTAMENTALES  Y JERARQUICOS
$sql = DB::PrepareSQL("INSERT IGNORE INTO edl_sp.evaluacion_p_funcional ( id_eval_fk, eval_funcional_id, eval_id_fk, valorAcordado_FK ) SELECT
edl_sp.q_edl2_base_funcional.evaluacion_id_fk,
edl_sp.q_edl2_base_funcional.evaluacion_p_id,
edl_sp.q_edl2_base_funcional.acuerdo_id,
edl_sp.q_edl2_base_funcional.valorAcordado 
FROM edl_sp.q_edl2_base_funcional;");
DB::Exec( $sql );

$sql = DB::PrepareSQL("INSERT IGNORE INTO edl_sp.evaluacion_p_comportamental ( id_eval_fk, evaluacion_p_id, acuerdo_id, idComportamental, idCompetencia, IdConducta ) SELECT
edl_sp.q_edl2_base_jerarquica.evaluacion_id_fk,
edl_sp.q_edl2_base_jerarquica.evaluacion_p_id,
edl_sp.q_edl2_base_jerarquica.acuerdo_id,
edl_sp.q_edl2_base_jerarquica.idComportamental,
edl_sp.q_edl2_base_jerarquica.idCompetencia,
edl_sp.q_edl2_base_jerarquica.IdConducta 
FROM edl_sp.q_edl2_base_jerarquica;");
DB::Exec( $sql );

$sql = DB::PrepareSQL("INSERT IGNORE INTO edl_sp.evaluacion_p_comportamental ( id_eval_fk, evaluacion_p_id, acuerdo_id, idComportamental, idCompetencia, IdConducta ) SELECT
edl_sp.q_edl2_base_comun.evaluacion_id_fk,
edl_sp.q_edl2_base_comun.evaluacion_p_id,
edl_sp.q_edl2_base_comun.acuerdo_id,
edl_sp.q_edl2_base_comun.idComportamental,
edl_sp.q_edl2_base_comun.idCompetencia,
edl_sp.q_edl2_base_comun.IdConducta 
FROM edl_sp.q_edl2_base_comun;");
DB::Exec( $sql );


$sql = DB::PrepareSQL("UPDATE
	edl_sp.evaluacion_p_funcional
	INNER JOIN
	edl_sp.compromisofuncional
	ON 
		edl_sp.evaluacion_p_funcional.eval_id_fk = edl_sp.compromisofuncional.id
		SET
	edl_sp.evaluacion_p_funcional.acuerdo = edl_sp.compromisofuncional.NomAcuerdo, 
	edl_sp.evaluacion_p_funcional.compromiso = edl_sp.compromisofuncional.compromisoFuncional, 
	edl_sp.evaluacion_p_funcional.evidencia = edl_sp.compromisofuncional.evidencia;");
DB::Exec( $sql );


$sql = DB::PrepareSQL("
UPDATE
	edl_sp.evaluacion_p_comportamental
	INNER JOIN
	edl_sp.comportamental_comun
	ON 
		edl_sp.evaluacion_p_comportamental.acuerdo_id = edl_sp.comportamental_comun.id AND
		edl_sp.evaluacion_p_comportamental.id_eval_fk = edl_sp.comportamental_comun.idEvaluacion_FK
		SET
	edl_sp.evaluacion_p_comportamental.Evidencia = edl_sp.comportamental_comun.Evidencia;");
DB::Exec( $sql );

$sql = DB::PrepareSQL("UPDATE
	edl_sp.evaluacion_p_comportamental
	INNER JOIN
	edl_sp.comportamental_jerarquica
	ON 
		edl_sp.evaluacion_p_comportamental.acuerdo_id = edl_sp.comportamental_jerarquica.id AND
		edl_sp.evaluacion_p_comportamental.id_eval_fk = edl_sp.comportamental_jerarquica.idEvaluacion_FK
		SET
	edl_sp.evaluacion_p_comportamental.Evidencia = edl_sp.comportamental_jerarquica.Evidencia;");
DB::Exec( $sql );


// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: After record processed
function BeforeMoveNextList(&$data, &$row, &$record, $recordId, $pageObject)
{

		if($data['estado'] == 1)
{
$pageObject->showItem("grid_edit", $recordId);
$pageObject->hideItem("BtnCal", $recordId); 
}
else
{
$pageObject->hideItem("grid_edit", $recordId);
$pageObject->showItem("BtnCal", $recordId); 
}

// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function BeforeMoveNextList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
