<?php
$securitySettings_var = array( 'providers' => array( array( 'type' => '%db',
'activationField' => 'active',
'active' => true,
'code' => '00',
'codeField' => 'totp',
'emailField' => 'email',
'extUserIdField' => '',
'fullnameField' => 'email',
'label' => array( 'text' => 'Database',
'type' => 0 ),
'name' => 'db',
'passwordField' => 'contrasenia',
'phoneField' => '˂Create new˃',
'resetDateField' => 'reset_date',
'resetTokenField' => 'reset_token',
'table' => array( 'connId' => 'edl_at_127_0_0_1',
'table' => 'usuario' ),
'twoFactorField' => 'two_factor',
'userGroupField' => 'groupid',
'usernameField' => 'usuario',
'userpicField' => 'userpic' ) ),
'sessionControl' => array( 'lifeTime' => 15,
'sessionName' => '6CCBXrQerySE4w1QyC0N',
'JWTSecret' => '94lUzkZiRkopF8ra4G1G' ),
'registration' => array( 'passwordValidation' => array( 'strong' => false,
'minimumLength' => 8,
'uniqueCharacters' => 4,
'digitsAndSymbols' => 2,
'upperAndLowerCase' => false ),
'remindMethod' => 1,
'hashAlgorithm' => 1,
'adminEmail' => '',
'caseInsensitiveLogin' => false,
'changePasswordPage' => true,
'changePwdPage' => true,
'hashPassword' => true,
'notifyAdmin' => false,
'notifyUser' => true,
'registerPage' => true,
'remindPage' => true,
'remindPasswordPage' => true,
'sendActivationLink' => false ),
'captchaSettings' => array( 'captchaType' => 0,
'siteKey' => '',
'secretKey' => '',
'passesCount' => 5 ),
'emailSettings' => array( 'fromEmail' => 'gestionsis@mincit.gov.co',
'usePHPDefinedSMTP' => false,
'useBuiltInMailer' => false,
'SMTPServer' => 'smtp.office365.com',
'SMTPPort' => 587,
'SMTPUser' => 'gestionsis@mincit.gov.co',
'SMTPPassword' => 'Mincomercio2022*',
'securityProtocol' => 2 ),
'advancedSecurity' => array( 'allowGuestLogin' => false,
'tables' => array( 'admin_members' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'admin_rights' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'admin_users' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'calificacion_definitiva' => array( 'mainOwnerIDField' => 'caldef_id',
'securityOption' => 0,
'userOwnerIDField' => 'id' ),
'cargo' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'competencia' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'comportamental' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'comportamental_comun' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'comportamental_comun_2' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'comportamental_comun_3' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'comportamental_comun_th' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'comportamental_jerarquica' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'comportamental_jerarquica_2' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'comportamental_jerarquica_3' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'comportamental_jerarquica_th' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'compromisofuncional' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'compromisofuncional_2' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'compromisofuncional_3' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'compromisofuncional_th' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'concertacion_po' => array( 'mainOwnerIDField' => 'sys_user',
'securityOption' => 1,
'userOwnerIDField' => 'usuario' ),
'concertacion_po_2' => array( 'mainOwnerIDField' => 'sys_user',
'securityOption' => 1,
'userOwnerIDField' => 'usuario' ),
'concertacion_po_3' => array( 'mainOwnerIDField' => 'idEvaluador',
'securityOption' => 1,
'userOwnerIDField' => 'idFuncionario' ),
'concertacion_po_3s' => array( 'mainOwnerIDField' => 'idEvaluador',
'securityOption' => 1,
'userOwnerIDField' => 'idFuncionario' ),
'concertacion_po_3se' => array( 'mainOwnerIDField' => 'idEvaluado',
'securityOption' => 1,
'userOwnerIDField' => 'idFuncionario' ),
'concertacion_th' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => 'usuario' ),
'conducta' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'dependencia' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'dependencias_001' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'evaluacion' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'evaluacion_p' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'evaluacion_p_comportamental' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'evaluacion_p_comportamental_th' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'evaluacion_p_funcional' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'evaluacion_p_funcional_th' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'evaluacion_p_th' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'evaluacion_po' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'evaluacion_seguimiento' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'evaluacion_x005' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'evaluador_final' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'evidencias_p' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'evidencias_p_th' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'funcionario' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'help' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'nombramiento' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'q_caldef_p_x005' => array( 'mainOwnerIDField' => 'idEvaluado',
'securityOption' => 1,
'userOwnerIDField' => 'id' ),
'q_caldef_p_x005_adm' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => 'id' ),
'q_caldef_p_x005_evaluador' => array( 'mainOwnerIDField' => 'idEvaluador',
'securityOption' => 1,
'userOwnerIDField' => 'idFuncionario' ),
'q_edl2_ctrl_valor_af_002' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'q_global_evaluadores' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'q_global_evaluadores_edl2' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'q_global_users_edl2' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'q_graph_estado Chart' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tparam_estados' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tparam_estados_calificacion' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tparam_estados_compromisos' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tparam_estados_eval' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tparam_estados_evaluacion_p' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tparam_periodo' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tparam_ponderacion' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tparam_puntaje' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tparam_tipoacuerdo' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tparam_vigencia' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tparam_vigencia_eval' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'usuario' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ) ) ),
'auditAndLocking' => array( 'loggingTable' => array( 'connId' => 'edl_at_127_0_0_1',
'table' => 'gestionedl_audit' ),
'lockingTable' => array( 'connId' => 'edl2_at_127_0_0_1',
'table' => '˂Create new˃' ),
'tables' => array( 'admin_members' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'admin_rights' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'admin_users' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'calificacion_definitiva' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cargo' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'competencia' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'comportamental' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'comportamental_comun' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'comportamental_comun_2' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'comportamental_comun_3' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'comportamental_comun_th' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'comportamental_jerarquica' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'comportamental_jerarquica_2' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'comportamental_jerarquica_3' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'comportamental_jerarquica_th' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'compromisofuncional' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'compromisofuncional_2' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'compromisofuncional_3' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'compromisofuncional_th' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'concertacion_po' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'concertacion_po_2' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'concertacion_po_3' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'concertacion_po_3s' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'concertacion_po_3se' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'concertacion_th' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'conducta' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'dependencia' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'dependencias_001' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'evaluacion' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'evaluacion_p' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'evaluacion_p_comportamental' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'evaluacion_p_comportamental_th' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'evaluacion_p_funcional' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'evaluacion_p_funcional_th' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'evaluacion_p_th' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'evaluacion_po' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'evaluacion_seguimiento' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'evaluacion_x005' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'evaluador_final' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'evidencias_p' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'evidencias_p_th' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'funcionario' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'help' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'nombramiento' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_caldef_p_x005' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_caldef_p_x005_adm' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_caldef_p_x005_evaluador' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_edl2_ctrl_valor_af_002' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_global_evaluadores' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tparam_estados' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tparam_estados_calificacion' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tparam_estados_compromisos' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tparam_estados_eval' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tparam_estados_evaluacion_p' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tparam_periodo' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tparam_ponderacion' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tparam_puntaje' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tparam_tipoacuerdo' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tparam_vigencia' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tparam_vigencia_eval' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'usuario' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ) ),
'loggingMode' => 1,
'loggingFile' => 'audit.log',
'logSecurityActions' => true,
'lockAfterUnsuccessfulLogin' => false,
'enableLocking' => false ),
'twoFactorSettings' => array( 'available' => true,
'required' => true,
'enable' => true,
'remember' => true,
'types' => array( 'email' => true,
'totp' => true ),
'twoFactorField' => 'two_factor',
'emailField' => 'email',
'phoneField' => '˂Create new˃',
'codeField' => 'totp',
'projectName' => 'GestionEDL' ),
'projectName' => 'GestionEDL_1091',
'loginDataSource' => 'usuario',
'loginForm' => 0,
'dynamicPermissions' => true,
'dpTablePrefix' => 'gestionedl_',
'dpTableConnId' => 'edl_at_127_0_0_1',
'hardcodedLogin' => false,
'enabled' => true,
'advancedSecurityAvailable' => true,
'userGroupsAvailable' => true,
'defaultProviderCode' => '00',
'adOnlyLogin' => false,
'dbProvider' => array( 'type' => '%db',
'activationField' => 'active',
'active' => true,
'code' => '00',
'codeField' => 'totp',
'emailField' => 'email',
'extUserIdField' => '',
'fullnameField' => 'email',
'label' => array( 'text' => 'Database',
'type' => 0 ),
'name' => 'db',
'passwordField' => 'contrasenia',
'phoneField' => '˂Create new˃',
'resetDateField' => 'reset_date',
'resetTokenField' => 'reset_token',
'table' => array( 'connId' => 'edl_at_127_0_0_1',
'table' => 'usuario' ),
'twoFactorField' => 'two_factor',
'userGroupField' => 'groupid',
'usernameField' => 'usuario',
'userpicField' => 'userpic' ),
'adAdminGroups' => array(  ),
'showUserSource' => false,
'dbProviderCodes' => array( '00' ),
'notifications' => array(  ) );
?>